### PR TITLE
fix: Properly close resources and handle errors in agent and storage. Fixes #3323

### LINKED ISSUE #3323: Memory leaks and hidden errors in agent and storage code
/kind bug

Currently, there are some places in the code base where resources are not properly closed (especially when defer is used within for loops, which results in memory leaks. The errors are also hidden. 

/assign @terrytangyuan

### PR DESCRIPTION
**Pull request by terrytangyuan**
Fixes https://github.com/kserve/kserve/issues/3323. This PR adds proper closure of resources and error handling for code related to agent and storage to avoid memory leaks and surface potential errors.

There are a few defer statements to release/close resources but they are within for loops, which lead to memory leaks.

### CODE REVIEW

File: pkg/agent/puller.go [hunk 1]
```diff
@@ -146,60 +146,72 @@ func (p *Puller) modelProcessor(modelName string, ops <-chan *ModelOp) {
...
-			if err != nil {
-				// If there is an error, we will NOT send a request. As such, to know about errors, you will
-				// need to call the error endpoint of the puller
-				p.logger.Errorf("Failed to download model %s with err %v", modelName, err)
-			} else {
-				// Load the model onto the model server
-				resp, err := http.Post(fmt.Sprintf("http://localhost:8080/v2/repository/models/%s/load", modelName),
-					"application/json",
-					bytes.NewBufferString("{}"))
+		func() {
```
Comment (dtrifiro) [inline pkg/agent/puller.go]: Nice catch here. 

How about extracting the function from the loop and using the occasion to further reduce indentation? Something like this maybe:

```diff
diff --git a/pkg/agent/puller.go b/pkg/agent/puller.go
index 683249ed..35f748fc 100644
--- a/pkg/agent/puller.go
+++ b/pkg/agent/puller.go
@@ -145,73 +145,74 @@ func (p *Puller) modelProcessor(modelName string, ops <-chan *ModelOp) {
 	// this is important for handling Load --> Unload requests sent in tandem
 	// Load --> Unload = 0 (cancel first load)
 	// Load --> Unload --> Load = 1 Load (cancel second load?)
-	for modelOp := range ops {
-		func() {
-			switch modelOp.Op {
-			case Add:
-				p.logger.Infof("Downloading model from %s", modelOp.Spec.StorageURI)
-				err := p.Downloader.DownloadModel(modelName, modelOp.Spec)
-				if err != nil {
-					// If there is an error, we will NOT send a request. As such, to know about errors, you will
-					// need to call the error endpoint of the puller
-					p.logger.Errorf("Failed to download model %s with err %v", modelName, err)
-				} else {
-					// Load the model onto the model server
-					resp, err := http.Post(fmt.Sprintf("http://localhost:8080/v2/repository/models/%s/load", modelName),
-						"application/json",
-						bytes.NewBufferString("{}"))
-					if err != nil {
-						// handle error
-						p.logger.Errorf("Failed to Load model %s", modelName)
-					} else {
-						defer func(Body io.ReadCloser) {
-							newErr := Body.Close()
-							if newErr != nil {
-								p.logger.Error(newErr, "failed to close body")
-							}
-						}(resp.Body)
-						if resp.StatusCode == 200 {
-							p.logger.Infof("Successfully loaded model %s", modelName)
-						} else {
-							body, err := io.ReadAll(resp.Body)
-							if err == nil {
-								p.logger.Infof("Failed to load model %s with status [%d] and resp:%v", modelName, resp.StatusCode, body)
-							}
-						}
-					}
+	var processOp = func(op *ModelOp) {
+		switch op.Op {
+		case Add:
+			p.logger.Infof("Downloading model from %s", op.Spec.StorageURI)
+			err := p.Downloader.DownloadModel(modelName, op.Spec)
+			if err != nil {
+				// If there is an error, we will NOT send a request. As such, to know about errors, you will
+				// need to call the error endpoint of the puller
+				p.logger.Errorf("Failed to download model %s with err %v", modelName, err)
+				return
+			}
+			// Load the model onto the model server
+			resp, err := http.Post(fmt.Sprintf("http://localhost:8080/v2/repository/models/%s/load", modelName),
+				"application/json",
+				bytes.NewBufferString("{}"))
+			if err != nil {
+				p.logger.Errorf("Failed to Load model %s", modelName)
+				return
+			}
+			defer func(body io.ReadCloser) {
+				newErr := body.Close()
+				if newErr != nil {
+					p.logger.Error(newErr, "failed to close body")
 				}
-			case Remove:
-				p.logger.Infof("unloading model %s", modelName)
-				// If there is an error, we will NOT do a delete... that could be problematic
-				if err := storage.RemoveDir(filepath.Join(p.Downloader.ModelDir, modelName)); err != nil {
-					p.logger.Error(err, "failing to delete model directory")
-				} else {
-					// unload model from model server
-					resp, err := http.Post(fmt.Sprintf("http://localhost:8080/v2/repository/models/%s/unload", modelName),
-						"application/json",
-						bytes.NewBufferString("{}"))
-					if err != nil {
-						// handle error
-						p.logger.Errorf("Failed to Unload model %s", modelName)
-					} else {
-						defer func(Body io.ReadCloser) {
-							newErr := Body.Close()
-							if newErr != nil {
-								p.logger.Error(newErr, "failed to close body")
-							}
-						}(resp.Body)
-						if resp.StatusCode == 200 {
-							p.logger.Infof("Successfully unloaded model %s", modelName)
-						} else {
-							body, err := io.ReadAll(resp.Body)
-							if err == nil {
-								p.logger.Infof("Failed to unload model %s with status [%d] and resp:%v", modelName, resp.StatusCode, body)
-							}
-						}
-					}
+			}(resp.Body)
+			if resp.StatusCode == 200 {
+				p.logger.Infof("Successfully loaded model %s", modelName)
+			} else {
+				body, err := io.ReadAll(resp.Body)
+				if err == nil {
+					p.logger.Infof("Failed to load model %s with status [%d] and resp:%v", modelName, resp.StatusCode, body)
 				}
 			}
-			p.completions <- modelOp
-		}()
+		case Remove:
+			p.logger.Infof("unloading model %s", modelName)
+			// If there is an error, we will NOT do a delete... that could be problematic
+			if err := storage.RemoveDir(filepath.Join(p.Downloader.ModelDir, modelName)); err != nil {
+				p.logger.Error(err, "failing to delete model directory")
+				return
+			}
+			// unload model from model server
+			resp, err := http.Post(fmt.Sprintf("http://localhost:8080/v2/repository/models/%s/unload", modelName),
+				"application/json",
+				bytes.NewBufferString("{}"))
+			if err != nil {
+				p.logger.Errorf("Failed to Unload model %s", modelName)
+				return
+			}
+			defer func(body io.ReadCloser) {
+				newErr := body.Close()
+				if newErr != nil {
+					p.logger.Error(newErr, "failed to close body")
+				}
+			}(resp.Body)
+			if resp.StatusCode == 200 {
+				p.logger.Infof("Successfully unloaded model %s", modelName)
+			} else {
+				body, err := io.ReadAll(resp.Body)
+				if err == nil {
+					p.logger.Infof("Failed to unload model %s with status [%d] and resp:%v", modelName, resp.StatusCode, body)
+				}
+			}
+		}
+		p.completions <- op
+
+	}
+
+	for op := range ops {
+		processOp(op)
 	}
 }

```

**Comment by terrytangyuan** [comment]
@dtrifiro Great idea! Updated.

File: pkg/agent/puller.go (hunk 1 above)
Comment (dtrifiro) [reply pkg/agent/puller.go]: @terrytangyuan nit:  another small update that might have been lost in the midst of that huge diff is using early returns in the switch statement, which would further reduce indentation and improve readability.

Comment (terrytangyuan) [reply pkg/agent/puller.go]: Thanks. I just updated the code to return earlier, except for the return right before defer statement since otherwise defer won't be executed.

Comment (terrytangyuan) [reply pkg/agent/puller.go]: Actually `return` also needs to be `break` instead since there's one more statement in that function that needs to be executed: `p.completions <- op`

File: pkg/agent/storage/https.go [hunk 2]
```diff
@@ -123,7 +128,10 @@ func (h *HTTPSDownloader) extractHeaders() (map[string]string, error) {
 	var headers map[string]string
 	hostname := h.Uri.Hostname()
 	headerJSON := os.Getenv(hostname + HEADER_SUFFIX)
-	json.Unmarshal([]byte(headerJSON), &headers)
+	err := json.Unmarshal([]byte(headerJSON), &headers)
+	if err != nil {
+		log.Error(err, "failed to unmarshal headers")
```
Comment (yuzisun) [inline pkg/agent/storage/https.go:133]: need to return err here

File: pkg/agent/storage/https.go [hunk 3]
```diff
@@ -172,15 +180,20 @@ func extractZipFiles(reader io.Reader, dest string) error {
...
 		if err != nil {
 			return fmt.Errorf("unable to open file: %v", err)
 		}
 
 		_, err = io.Copy(file, rc)
-		file.Close()
-		rc.Close()
+		newErr := file.Close()
+		if newErr != nil {
+			log.Error(newErr, "failed to close file")
```
Comment (yuzisun) [inline pkg/agent/storage/https.go]: return newErr

File: pkg/agent/storage/s3.go [hunk 4]
```diff
@@ -114,7 +114,12 @@ func (s *S3ObjectDownloader) GetAllObjects(s3Svc s3iface.S3API) ([]s3manager.Bat
 			},
 			Writer: file,
 			After: func() error {
-				defer file.Close()
+				defer func(file *os.File) {
+					newErr := file.Close()
```
Comment (yuzisun) [inline pkg/agent/storage/s3.go]: nit: newErr -> closeErr

File: pkg/agent/puller.go [hunk 5]
```diff
@@ -179,27 +184,35 @@ func (p *Puller) modelProcessor(modelName string, ops <-chan *ModelOp) {
...
-					bytes.NewBufferString("{}"))
-				if err != nil {
-					// handle error
-					p.logger.Errorf("Failed to Unload model %s", modelName)
+				defer func(Body io.ReadCloser) {
+					newErr := Body.Close()
+					if newErr != nil {
+						p.logger.Error(newErr, "failed to close body")
+					}
+				}(resp.Body)
```
Comment (yuzisun) [inline pkg/agent/puller.go]: if resp is nil then this will panic
 ```go
 if resp != nil {
    defer resp.Body.Close()
 }
 ```

Comment (yuzisun) [reply pkg/agent/puller.go]: also is it a good practice to check the error from `Close()`? most of the go lang examples I have seen do not check this

File: pkg/agent/storage/utils.go [hunk 6]
```diff
@@ -73,7 +73,12 @@ func RemoveDir(dir string) error {
 	if err != nil {
 		return err
 	}
-	defer d.Close()
+	defer func(d *os.File) {
+		newErr := d.Close()
```
Comment (yuzisun) [inline pkg/agent/storage/utils.go]: nit: newErr -> closeErr

File: pkg/agent/watcher.go [hunk 7]
```diff
@@ -83,7 +83,12 @@ func (w *Watcher) Start() {
 		w.logger.Error(err, "Failed to create model dir watcher")
 		panic(err)
 	}
-	defer watcher.Close()
+	defer func(watcher *fsnotify.Watcher) {
+		newErr := watcher.Close()
```
Comment (yuzisun) [inline pkg/agent/watcher.go]: nit: newErr -> closeErr

Comment (terrytangyuan) [reply pkg/agent/watcher.go]: Updated

File: pkg/agent/storage/utils.go (hunk 6 above)
Comment (terrytangyuan) [reply pkg/agent/storage/utils.go]: Updated

File: pkg/agent/puller.go (hunk 5 above)
Comment (terrytangyuan) [reply pkg/agent/puller.go]: Updated. I have seen it quite often in other projects.

File: pkg/agent/storage/s3.go (hunk 4 above)
Comment (terrytangyuan) [reply pkg/agent/storage/s3.go]: Updated

File: pkg/agent/storage/https.go (hunk 3 above)
Comment (terrytangyuan) [reply pkg/agent/storage/https.go]: Updated

File: pkg/agent/storage/https.go (hunk 2 above)
Comment (terrytangyuan) [reply pkg/agent/storage/https.go:133]: This was intentionally not returned since there are existing test cases that assume we still download the model even when there are errors during unmarshaling. I didn't want to break the existing logic so I only logged the error instead returning it.

File: pkg/agent/puller.go [hunk 8]
```diff
@@ -179,27 +184,37 @@ func (p *Puller) modelProcessor(modelName string, ops <-chan *ModelOp) {
...
-					defer resp.Body.Close()
-					if resp.StatusCode == 200 {
-						p.logger.Infof("Successfully unloaded model %s", modelName)
-					} else {
-						body, err := io.ReadAll(resp.Body)
-						if err == nil {
-							p.logger.Infof("Failed to unload model %s with status [%d] and resp:%v", modelName, resp.StatusCode, body)
+				if resp != nil {
+					defer func(Body io.ReadCloser) {
+						newErr := Body.Close()
```
Comment (yuzisun) [inline pkg/agent/puller.go]: newErr -> closeErr

File: pkg/agent/storage/gcs.go [hunk 9]
```diff
@@ -123,7 +123,12 @@ func (g *GCSObjectDownloader) DownloadFile(client stiface.Client, attrs *gstorag
 			err,
 		)
 	}
-	defer reader.Close()
+	defer func(reader stiface.Reader) {
+		newErr := reader.Close()
```
Comment (yuzisun) [inline pkg/agent/storage/gcs.go]: closeErr

File: pkg/agent/storage/gcs.go [hunk 10]
```diff
@@ -146,6 +150,12 @@ func (g *GCSObjectDownloader) WriteToFile(data []byte, attrs *gstorage.ObjectAtt
 			err,
 		)
 	}
+	defer func(file *os.File) {
+		newErr := file.Close()
```
Comment (yuzisun) [inline pkg/agent/storage/gcs.go]: closeErr

File: pkg/agent/storage/https.go [hunk 11]
```diff
@@ -85,7 +85,12 @@ func (h *HTTPSDownloader) Download(client http.Client) error {
 		return fmt.Errorf("failed to make a request: %v", err)
 	}
 
-	defer resp.Body.Close()
+	defer func(Body io.ReadCloser) {
+		newErr := Body.Close()
```
Comment (yuzisun) [inline pkg/agent/storage/https.go]: NewErr -> closeErr

File: pkg/agent/storage/https.go [hunk 12]
```diff
@@ -172,15 +180,20 @@ func extractZipFiles(reader io.Reader, dest string) error {
...
-
 		rc, err := zipFile.Open()
 		if err != nil {
 			return fmt.Errorf("unable to open file: %v", err)
 		}
 
 		_, err = io.Copy(file, rc)
-		file.Close()
-		rc.Close()
+		newErr := file.Close()
```
Comment (yuzisun) [inline pkg/agent/storage/https.go]: CloseErr

File: pkg/agent/storage/https.go [hunk 13]
```diff
@@ -193,7 +206,12 @@ func extractTarFiles(reader io.Reader, dest string) error {
 	if err != nil {
 		return err
 	}
-	defer gzr.Close()
+	defer func(gzr *gzip.Reader) {
+		newErr := gzr.Close()
```
Comment (yuzisun) [inline pkg/agent/storage/https.go]: CloseErr

Comment (terrytangyuan) [reply pkg/agent/storage/https.go]: Replaced all with `closeErr`
