### PR TITLE
Fix the issue of Invalid value for env[1].valueFrom

### LINKED ISSUE #4761: spec.initContainers[0].env[1].valueFrom: Invalid value: ""
/kind bug

**What steps did you take and what happened:**

When I create the inference service, it failed to launch the pod. The deployment is there, but not the pod.
The deployment resource gave me the following error:
```
[spec.initContainers[0].env[1].valueFrom: Invalid value: "": may not be specified
      when `value` is not empty, spec.initContainers[0].env[2].valueFrom: Invalid
      value: "": may not be specified when `value` is not empty]
```

This error seems to indicate conflicting value and valueFrom fields set in the container env.
The error was introduced by this PR: https://github.com/kserve/kserve/pull/4726

If we remove the section 
```
			Env: []corev1.EnvVar{
				{
					Name:  "HF_HUB_ENABLE_HF_TRANSFER",
					Value: "1",
				},
				{
					Name:  "HF_XET_HIGH_PERFORMANCE",
					Value: "1",
				},
				{
					Name:  "HF_XET_NUM_CONCURRENT_RANGE_GETS",
					Value: "8",
				},
			},
```
from the file pkg/utils/storage.go, the issue is gone.

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by houshengbo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4761

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

File: pkg/webhook/admission/pod/storage_initializer_injector.go [hunk 1]
```diff
@@ -488,6 +488,11 @@ func CommonStorageInitialization(ctx context.Context, params *StorageInitializer
 				return err
 			}
 		}
+
+		// Add default HuggingFace optimization environment variables if they don't already exist.
+		// This is done after merging to avoid conflicts with user-defined environment variables.
```
Comment (brettmthompson) [inline pkg/webhook/admission/pod/storage_initializer_injector.go:518]: So root cause for https://github.com/kserve/kserve/issues/4761 is when non-default user-defined env variables are configured for `HF_HUB_ENABLE_HF_TRANSFER` , `HF_XET_HIGH_PERFORMANCE`, or `HF_XET_NUM_CONCURRENT_RANGE_GETS`. 

This is a good catch. I think this vulnerability would have been present even when only `HF_TRANSFER` was set in [hf_secret.go](https://github.com/kserve/kserve/blob/release-0.15/pkg/credentials/hf/hf_secret.go#L38).

This raises the question - should we also apply the logic to setting env variables for other storage types as well, for example when setting env variables for [s3 storage](https://github.com/kserve/kserve/blob/release-0.15/pkg/credentials/s3/utils.go#L32)?

Comment (houshengbo) [reply pkg/webhook/admission/pod/storage_initializer_injector.go:518]: I think pkg/webhook/admission/pod/storage_initializer_injector.go has general functions to call by all type of storage. Or does each type of storage have its implementation?

Comment (brettmthompson) [reply pkg/webhook/admission/pod/storage_initializer_injector.go:518]: If a storage spec is utilized then a [generic function](https://github.com/kserve/kserve/blob/master/pkg/credentials/service_account_credentials.go#L101) is used for all storage types to create the container env.

On the other, if a storage spec is not utilized then the container envs are created for each storage type via a different [implementation.](https://github.com/kserve/kserve/blob/master/pkg/credentials/service_account_credentials.go#L271) . These differing implementations can be found in the subfolders in this [directory](https://github.com/kserve/kserve/tree/master/pkg/credentials).

Comment (houshengbo) [reply pkg/webhook/admission/pod/storage_initializer_injector.go:518]: @brettmthompson I investigated this thoroughly and here's what I found:

### S3 and Other Storage Credentials Are Safe 

The good news is that S3, GCS, Azure, and other storage credential environment variables do **not** have the same vulnerability. Here's why:

1. **Credential env vars use `ValueFrom`**: 
   - Variables like `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` are injected using `ValueFrom.SecretKeyRef`
   - These are added by `CreateSecretVolumeAndEnv()` in `service_account_credentials.go` (lines 404-430 of storage_initializer_injector.go)
   - Since they use `ValueFrom`, even if a user tries to override them, the strategic merge patch won't create a Value/ValueFrom conflict.

2. **S3 configuration env vars are conditionally added**:
   - Variables like `S3_ENDPOINT`, `S3_USE_HTTPS`, `S3_VERIFY_SSL`, etc. are built by `BuildS3EnvVars()` in `pkg/credentials/s3/utils.go`
   - Each var is only added **if it has a non-empty value** (see lines 36-115 in s3/utils.go)
   - They all use `Value` (not `ValueFrom`), so if a user tries to set the same var with `ValueFrom`, it would fail - but this is unlikely since users typically use storage secrets

3. **These env vars are appended after init container creation**:
   - They're added **before** the `mergeContainerSpecs` call 
   - But since credentials use `ValueFrom` and configs use `Value`, there's no same-field conflict

### The HF Env Vars Were a Unique Case

The HF optimization env vars (`HF_HUB_ENABLE_HF_TRANSFER`, `HF_XET_HIGH_PERFORMANCE`, `HF_XET_NUM_CONCURRENT_RANGE_GETS`) were unique because they:
- Were **hardcoded with `Value = "1"`** inside `CreateInitContainerWithConfig()`
- Were meant to be **generic optimizations** (not credentials)
- Could reasonably be customized by users (e.g., disabling transfer acceleration, using different values from ConfigMaps)

### Potential Edge Case: CA Bundle Env Vars ⚠️

There is **one other place** that could theoretically have the same issue - the CA bundle env vars at lines 453-461:

```go
initContainer.Env = append(initContainer.Env, corev1.EnvVar{
    Name:  constants.CaBundleConfigMapNameEnvVarKey,
    Value: caBundleConfigMapName,
})
initContainer.Env = append(initContainer.Env, corev1.EnvVar{
    Name:  constants.CaBundleVolumeMountPathEnvVarKey,
    Value: caBundleVolumeMountPath,
})
```


If we want to be extra cautious, we could also apply the same defensive pattern to the CA bundle env vars, but it's not as critical since those are rarely customized by users.

I can apply the same pattern to CA bundle env vars as a preventive measure.

Comment (brettmthompson) [reply pkg/webhook/admission/pod/storage_initializer_injector.go:518]: Thank you for the thorough investigation @houshengbo

File: pkg/webhook/admission/pod/storage_initializer_injector.go [hunk 2]
```diff
@@ -481,13 +514,10 @@ func CommonStorageInitialization(ctx context.Context, params *StorageInitializer
...
-		if params.StorageContainerSpec != nil {
-			err := mergeContainerSpecs(initContainer, &params.StorageContainerSpec.Container)
-			if err != nil {
-				return err
-			}
-		}
+		// Add default HuggingFace optimization environment variables if they don't already exist.
+		// This is done after merging to avoid conflicts with user-defined environment variables.
+		// See https://github.com/kserve/kserve/issues/4761
+		utils.AddDefaultHuggingFaceEnvVars(initContainer)
```
Comment (brettmthompson) [inline pkg/webhook/admission/pod/storage_initializer_injector.go:520]: Would it be beneficial to only add the hugging face related values to the container env if the storage uris set in the  `StorageInitializerParams` input param contain a hugging face uri?

**Comment by brettmthompson** [comment]
@houshengbo the [changes](https://github.com/kserve/kserve/pull/4765/commits/fb51bf4d8ba03f8b90193970095df51f5b1941e6) for ca bundle env vars would also apply to the logic used for llmisvcs [here](https://github.com/kserve/kserve/blob/master/pkg/controller/v1alpha1/llmisvc/workload_storage.go#L264). As I don't want to put more work on your plate, I can make the changes for llmisvcs in a separate PR.

File: pkg/webhook/admission/pod/storage_initializer_injector.go (hunk 2 above)
Comment (houshengbo) [reply pkg/webhook/admission/pod/storage_initializer_injector.go:520]: I think keeping them unconditional is better because: 
(1) they're harmless when unused.
(2) HF libraries only activate for hf:// URIs anyway.
(3) it keeps the code simpler. If needed, users can override them through the storage container spec.

**Comment by houshengbo** [comment]
@brettmthompson You're right that the CA bundle env var logic in `pkg/controller/v1alpha1/llmisvc/workload_storage.go` would benefit from the same defensive pattern.

Thanks for the thorough review!

**Comment by houshengbo** [comment]
https://github.com/kserve/kserve/pull/4777/files i opened another pr as well.

**Comment by brettmthompson** [comment]
LGTM

**Review by yuzisun — APPROVED** [review]
