### PR TITLE
Fix streaming response not working properly with logger

### LINKED ISSUE #3809: Enabling inference service logging disables streaming responses
/kind bug

**What steps did you take and what happened:**

If you enable logging, the agent sidecar added breaks streaming responses.   Instead of a streamed responses, the caller only gets any response data after the full response has been created.

**What did you expect to happen:**

The streamed response should start and the caller should see each streamed token as they are generated.

**What's the InferenceService yaml:**

Here is the fully functional LLM inference service using a public docker image that can be used to reproduce the problem.
Normally, we have a custom logger to handle the logging, but I have omitted it to simply this example.

custom-model.yaml:
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-model
spec:
  predictor:
   # Adding the logger, introduces the agent sidecar which breaks streaming responses
   # Comment out to get expected behavior.
   logger:
      mode: all
   containers:
    - name: kserve-container
      image: jjharrow/facebook-pt-125m-service
      env:
        - name: BENTOML_HOME
          value: /home/bentoml/bento
      args:
        - openllm
        - start
        - --port
        - "8080"
        - --backend=pt
        - --dtype=float32
        - facebook/opt-125m
      ports:
        - containerPort: 8080
```

kubectl apply -f  custom-model.yaml

Once successfully deployed/started get the service address

`HOST={inferenceServiceAddress}`

You can show the behavior using the script `read-stream.sh` to invoke a streaming inference and show timestamps on the responses.   When streaming properly the first response takes about 3-4 secs for me, with the rest completing over the next 5 seconds or so (depending on how long the response is).   When logging is enabled, instead the first response takes 8 seconds with all the output essentially happening at the same time.

read-stream.sh
```
#/bin/bash
# Usage: read-stream.sh http://custom-model.default.cluster.local
HOST=$1

printf '[%s]\n' "$(date '+%Y-%m-%d %H:%M:%S')"
curl -s $HOST/v1/generate_stream -H 'accept: text/event-stream' -H 'Content-Type: application/json' \
  -d '{"prompt": "What is the meaning of life?"}' \
  | while IFS= read -r line; do printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$line"; done
```

With logging enabled:

```
./read-stream.sh $HOST
[2024-07-19 10:52:49]
[2024-07-19 10:52:57] data: {"prompt":"What is the meaning of life?","finished":false,"outputs":[{"index":0,"text":"\n","token_ids":[50118],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[2,2264,16,5,3099,9,301,116],"prompt_logprobs":null,"request_id":"openllm-200254079ce84ebda5980c34bffd0d24"}
...
[2024-07-19 10:52:58] data: [DONE]
```

With logging disabled:
```
./read-stream.sh $HOST
[2024-07-19 10:55:59]
[2024-07-19 10:56:03] data: {"prompt":"What is the meaning of life?","finished":false,"outputs":[{"index":0,"text":"\n","token_ids":[50118],"cumulative_logprob":0.0,"logprobs":null,"finish_reason":null}],"prompt_token_ids":[2,2264,16,5,3099,9,301,116],"prompt_logprobs":null,"request_id":"openllm-7977401451b14bb59c13e92865a91047"}
...
[2024-07-19 10:56:07] data: [DONE]
```

From a python environment you can demonstrate it with the openllm.   It is more visual since you can see each word print one at a time, instead of getting the whole response in a single print.

```
pip install openllm==0.4.44 openllm-client==0.4.44
openllm query --endpoint $HOST hello
hello! i'm a new player too! i just started playing. i just want to know what i can do to improve my game. i have a lot of stuff to learn but i'm not sure if i can really improve my game in a very specific way. i'm also new to this game and i'm learning alot. i just want to know if i can improve my game or if i should just continue playing and play. thanks!

Hello, i'm a new player too! i just started playing. i just want to know what i can do to improve my game. i have a lot of stuff to learn but
```

**Anything else you would like to add:**

Any potential workaround suggestions would be appreciated.

**Environment:**

Reproducible with:
curl -s "https://raw.githubusercontent.com/kserve/kserve/release-0.12/hack/quick_install.sh" | bash

- Cloud Environment: GKE cluster 
- Kubernetes version: (use `kubectl version`):
GKE cluster
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.10-gke.1075001
Docker Desktop K8s:
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
- OS (e.g. from `/etc/os-release`):
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_METRICS_PRODUCT_ID=26
KERNEL_COMMIT_ID=1a8b1dfd94df6f28729aca0565343c0a9f6906ee
GOOGLE_CRASH_ID=Lakitu
VERSION=109
VERSION_ID=109
BUILD_ID=17800.218.69
--
Also reproduced on MacOs Apple M2 Max, 14.5 (23F79)

### PR DESCRIPTION
**Pull request by sivanantha321**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
- Fixes #3809

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
Fix streaming response not working properly with logger
```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

File: pkg/logger/handler.go [hunk 1]
```diff
@@ -105,15 +136,18 @@ func (eh *LoggerHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
-	contentType = rr.Header().Get("Content-Type")
-	if contentType != "" {
-		w.Header().Set("Content-Type", contentType)
+	// TODO: Set a reasonable intial buffer size
+	var responseBuf bytes.Buffer
+	lrw := &loggingResponseWriter{ResponseWriter: w, responseBuffer: &responseBuf, log: eh.log}
+	eh.next.ServeHTTP(lrw, r)
+	// Read the response body from the buffer
+	reader := bufio.NewReader(lrw.responseBuffer)
+	responseBody, err := io.ReadAll(reader)
```
Comment (sivanantha321) [inline pkg/logger/handler.go:160]: Currently, We are collecting all the streamed data and sending it as a single cloudevent to the logger (that's how it was done previously so I am just keeping it as it is). Should we consider sending each chunck as a separate cloudevent ? This approach will also reduce the memory footprint of agent sidecar.

Comment (jerryharrow) [reply pkg/logger/handler.go:160]: So previously we had the full eventstream response body, in the cloudevent?
I didn't realize that.  Useful.

A single cloudevent is certainly easier to process from a consumer perspective, but multiple events (as long as it is possible to interpret it as multiple response events for the same stream and put it back together when analyzing the cloudevents).

File: pkg/logger/handler.go [hunk 2]
```diff
@@ -105,15 +136,18 @@ func (eh *LoggerHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
-		w.Header().Set("Content-Type", contentType)
+	// TODO: Set a reasonable initial buffer size
+	var responseBuf bytes.Buffer
+	lrw := &loggingResponseWriter{ResponseWriter: w, responseBuffer: &responseBuf, log: eh.log}
+	eh.next.ServeHTTP(lrw, r)
+	// Read the response body from the buffer
+	reader := bufio.NewReader(lrw.responseBuffer)
+	responseBody, err := io.ReadAll(reader)
+	if err != nil {
+		eh.log.Error(err, "Failed to read response body")
```
Comment (jerryharrow) [inline pkg/logger/handler.go:147]: Anything in the err that you should perhaps include in this message?

File: pkg/logger/handler.go (hunk 1 above)
Comment (sivanantha321) [reply pkg/logger/handler.go:160]: We have [cloudevent id](https://github.com/kserve/kserve/pull/3847/files#diff-d6234b161cbbad078660d85ab2911474143501480664e5e5ca2395d25c4378b3R157) which allows us to identify that a specific stream belongs to a certain request-response cycle.

**Comment by jerryharrow** [comment]
Seems like all is in order -- @yuzisun @terrytangyuan what else is needed here?

**Review by terrytangyuan — COMMENTED** [review]
@ruivieira Does TrustyAI rely on this?

**Comment by ruivieira** [comment]
> @ruivieira Does TrustyAI rely on this?

@terrytangyuan This will potentially affect TrustyAI but, IIUC, we can just reconcile the cloudevents by id and then continue processing as previously.

**Review by terrytangyuan — CHANGES_REQUESTED** [review]
There's a risk of breaking compatibility.

**Comment by sivanantha321** [comment]
> There's a risk of breaking compatibility.

I believe there is no breaking change. Previously we had two cloudevents one for request and one for response. This PR also does the same thing. One cloudevent for request and one cloudevent for response. The response cloudevent will collect all the chunks and send it as a single cloudevent.

I proposed that each streaming chunk can have separate cloudevent but that is not implemented. https://github.com/kserve/kserve/pull/3847/files#r1708972985

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by terrytangyuan** [comment]
@jerryharrow Would you like to add your company in this list if you are using KServe? https://github.com/kserve/website/blob/main/docs/community/adopters.md

**Comment by jerryharrow** [comment]
> @jerryharrow Would you like to add your company in this list if you are using KServe? https://github.com/kserve/website/blob/main/docs/community/adopters.md

Absolutely.   Like this?  https://github.com/kserve/website/pull/403
