### PR TITLE
Fix knative config-defaults values overrided by kserve

### LINKED ISSUE #3092: Is is possible to set a default value of InferenceService's timeout (Serverless mode)
/kind question

**What's the question**
I found that a pod created by KServe takes long time to be terminated (300 seconds).
As I understand, `terminationGracePeriodSeconds` in the pod config controls this behavior and we can configure it per InferenceService by `timeout` (Ref: https://github.com/kserve/kserve/issues/1546). 
However, I'd like to decrease this value for all ISVC in our platform, because they take too long time to evict their pods during K8S node operation.
Would it be possible to set a default value of InferenceService's timeout? 

Btw, the below shows my experiment with adjusting a default value at KNative Serving side. It doesn't work.

**What's the InferenceService yaml:**
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: pytorch-mnist
  namespace: default
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      storageUri: gs://kfserving-examples/models/torchserve/image_classifier/v2

```

**What steps did you take and what happened:**
1. Set a default value of `revision-timeout-seconds` in KNative 
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: knative-serving
  name: config-defaults
  namespace: knative-serving
data:
  revision-timeout-seconds: "120"
```
2. Restart KNative controller
3. Deploy the above KServe's InferenceService
4. `terminationGracePeriodSeconds` in InferenceService's pod is still set to `300`

**Environment:**

- Istio Version: v1.18.0
- Knative Version: v1.10.2
- KServe Version: v0.10.1
- Kubeflow version: N/A
- Cloud Environment: AWS
- Minikube/Kind version:
- Kubernetes version: 1.24
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by sivanantha321**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3092

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go [hunk 1]
```diff
@@ -179,7 +181,11 @@ func createKnativeService(componentMeta metav1.ObjectMeta,
 	}
 	//Call setDefaults on desired knative service here to avoid diffs generated because knative defaulter webhook is
 	//called when creating or updating the knative service
-	service.SetDefaults(context.TODO())
+	// Before calling setDefaults load the knative configmap into the context to avoid overriding the knative configmap values.
+	ctx := context.TODO()
+	knConfigStore := knservingconfig.NewStore(knlogging.FromContext(ctx).Named(constants.KnativeReconcilerName))
+	ctx = knservingconfig.ToContext(ctx, knConfigStore.Load())
+	service.SetDefaults(ctx)
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go]: I think probably not good idea to add too much Knative dependency here, calling dry-run could be a better option to get the expected object.

https://github.com/kserve/kserve/blob/1cc7e6c94eb848ba934eb75129ffba44db1fe2ed/pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go#L103

Comment (sivanantha321) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go]: Done. Thanks for the suggestion :)

File: pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go [hunk 2]
```diff
@@ -227,6 +225,19 @@ func (r *KsvcReconciler) Reconcile() (*knservingv1.ServiceStatus, error) {
 		}
 		return nil, err
 	}
+	// Set ResourceVersion which is required for update operation.
+	desired.ResourceVersion = existing.ResourceVersion
```
Comment (sivanantha321) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go:228]: @yuzisun From K8s docs: You can overwrite (update) an existing resource - for example, a ConfigMap - using an HTTP PUT. For a PUT request, it is the client's responsibility to specify the resourceVersion (taking this from the object being updated). Kubernetes uses that resourceVersion information so that the API server can detect lost updates and reject requests made by a client that is out of date with the cluster. In the event that the resource has changed (the resourceVersion the client provided is stale), the API server returns a 409 Conflict error response.

https://kubernetes.io/docs/reference/using-api/api-concepts/#patch-and-apply

https://github.com/argoproj/argo-cd/issues/3657#issuecomment-722706739

https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/53#issuecomment-874186845

https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/53#issuecomment-874751106

File: pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go [hunk 3]
```diff
@@ -227,6 +225,19 @@ func (r *KsvcReconciler) Reconcile() (*knservingv1.ServiceStatus, error) {
...
+	// Add immutable annotations to avoid validation error during dry-run update.
+	desired.Annotations[knserving.CreatorAnnotation] = existing.Annotations[knserving.CreatorAnnotation]
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go:230]: Is updatorAnnotation immutable ? The updator for desired service can be different from existing service.

File: pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go [hunk 4]
```diff
@@ -227,6 +225,19 @@ func (r *KsvcReconciler) Reconcile() (*knservingv1.ServiceStatus, error) {
...
+	desired.Annotations[knserving.UpdaterAnnotation] = existing.Annotations[knserving.UpdaterAnnotation]
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go:231]: Is updatorAnnotation immutable ? The updator for desired service can be different from existing service.

File: pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go (hunk 3 above)
Comment (sivanantha321) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go:230]: No updatorAnnotation is not immutable. Only the creatorAnnotation is immutable.

Comment (yuzisun) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go:230]: Right, my question is that the desired `updatedAnnotation` can be different from existing one, so we should not set the desired updator annotation to the existing updator annotation right?

Comment (yuzisun) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go:230]: Discussed with @sivanantha321 Knative has the check to prevent user setting the `updatorAnnotation`.
