### PR TITLE
Bump golang-lint to 1.63 and fix all linter errors

### LINKED ISSUE #4201: Golang linter reports several issues
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Tried linter with the latest golang linter version.

**What did you expect to happen:**

Linter passes 
**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

under pkg for example I get (golangci-lint-1.63.4-linux-amd64/golangci-lint run  ./pkg/...):
```
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`. 
WARN [config_reader] The configuration option `output.uniq-by-line` is deprecated, please use `issues.uniq-by-line` 
WARN [config_reader] The configuration option `output.format` is deprecated, please use `output.formats` 
WARN [config_reader] The output format `github-actions` is deprecated, please use `colored-line-number` 
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar. 
::error file=pkg/apis/serving/v1alpha1/inference_graph_validation.go,line=190,col=9::SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
::error file=pkg/apis/serving/v1beta1/component.go,line=178,col=10::SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
::error file=pkg/apis/serving/v1beta1/component.go,line=181,col=10::SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
::error file=pkg/apis/serving/v1beta1/component.go,line=184,col=10::SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
::error file=pkg/apis/serving/v1beta1/component.go,line=194,col=10::SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
::error file=pkg/apis/serving/v1beta1/component.go,line=202,col=11::SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
::error file=pkg/apis/serving/v1beta1/predictor_tfserving.go,line=62,col=21::printf: non-constant format string in call to fmt.Errorf (govet)
::error file=pkg/apis/serving/v1beta1/predictor_tfserving.go,line=66,col=21::printf: non-constant format string in call to fmt.Errorf (govet)
::error file=pkg/apis/serving/v1beta1/predictor_torchserve.go,line=61,col=10::SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
::error file=pkg/apis/serving/v1beta1/predictor_torchserve.go,line=65,col=10::SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
::high file=pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go,line=64,col=22::G115: integer overflow conversion int -> int32 (gosec)
::high file=pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go,line=70,col=22::G115: integer overflow conversion int -> int32 (gosec)
::high file=pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go,line=97,col=22::G115: integer overflow conversion int -> int32 (gosec)
::high file=pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go,line=99,col=22::G115: integer overflow conversion int -> int32 (gosec)
::high file=pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go,line=102,col=22::G115: integer overflow conversion int -> int32 (gosec)
::high file=pkg/webhook/admission/pod/metrics_aggregate_injector.go,line=77,col=25::G115: integer overflow conversion int -> int32 (gosec)
pkg/apis/serving/v1alpha1/inference_graph_validation.go:190:9: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
	return fmt.Errorf(RootNodeNotFoundError)
	       ^
pkg/apis/serving/v1beta1/component.go:178:10: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
		return fmt.Errorf(MinReplicasLowerBoundExceededError)
		       ^
pkg/apis/serving/v1beta1/component.go:181:10: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
		return fmt.Errorf(MaxReplicasLowerBoundExceededError)
		       ^
pkg/apis/serving/v1beta1/component.go:184:10: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
		return fmt.Errorf(MinReplicasShouldBeLessThanMaxError)
		       ^
pkg/apis/serving/v1beta1/component.go:194:10: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
		return fmt.Errorf(ParallelismLowerBoundExceededError)
		       ^
pkg/apis/serving/v1beta1/component.go:202:11: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
			return fmt.Errorf(InvalidLoggerType)
			       ^
pkg/apis/serving/v1beta1/predictor_tfserving.go:62:21: printf: non-constant format string in call to fmt.Errorf (govet)
		return fmt.Errorf(InvalidTensorflowRuntimeIncludesGPU)
		                  ^
pkg/apis/serving/v1beta1/predictor_tfserving.go:66:21: printf: non-constant format string in call to fmt.Errorf (govet)
		return fmt.Errorf(InvalidTensorflowRuntimeExcludesGPU)
		                  ^
pkg/apis/serving/v1beta1/predictor_torchserve.go:61:10: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
		return fmt.Errorf(InvalidPyTorchRuntimeIncludesGPU)
		       ^
pkg/apis/serving/v1beta1/predictor_torchserve.go:65:10: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
		return fmt.Errorf(InvalidPyTorchRuntimeExcludesGPU)
		       ^
pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:64:22: G115: integer overflow conversion int -> int32 (gosec)
		utilization = int32(utilizationInt) // #nosec G109
		                   ^
pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:70:22: G115: integer overflow conversion int -> int32 (gosec)
		utilization = int32(*componentExt.ScaleTarget)
		                   ^
pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:97:22: G115: integer overflow conversion int -> int32 (gosec)
		minReplicas = int32(constants.DefaultMinReplicas)
		                   ^
pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:99:22: G115: integer overflow conversion int -> int32 (gosec)
		minReplicas = int32(*componentExt.MinReplicas)
		                   ^
pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:102:22: G115: integer overflow conversion int -> int32 (gosec)
	maxReplicas := int32(componentExt.MaxReplicas)
	                    ^
pkg/webhook/admission/pod/metrics_aggregate_injector.go:77:25: G115: integer overflow conversion int -> int32 (gosec)
				ContainerPort: int32(constants.QueueProxyAggregatePrometheusMetricsPort),
```

### PR DESCRIPTION
**Pull request by sivanantha321**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4201 

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
Bump golang-lint to 1.61 to support go 1.22
```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

File: pkg/constants/constants.go [hunk 1]
```diff
@@ -81,26 +81,26 @@ const (
...
+	EnableMetricAggregation                           = KServeAPIGroupName + "/enable-metric-aggregation"
+	SetPrometheusAnnotation                           = KServeAPIGroupName + "/enable-prometheus-scraping"
+	KserveContainerPrometheusPortKey                  = "prometheus.kserve.io/port"
+	KServeContainerPrometheusPathKey                  = "prometheus.kserve.io/path"
+	PrometheusPortAnnotationKey                       = "prometheus.io/port"
+	PrometheusPathAnnotationKey                       = "prometheus.io/path"
+	StorageReadonlyAnnotationKey                      = "storage.kserve.io/readonly"
+	DefaultPrometheusPath                             = "/metrics"
+	QueueProxyAggregatePrometheusMetricsPort    int32 = 9088
+	DefaultPodPrometheusPort                          = "9091"
```
Comment (spolti) [inline pkg/constants/constants.go]: should we use int here as well?

File: pkg/webhook/admission/pod/metrics_aggregate_injector.go [hunk 2]
```diff
@@ -108,7 +109,7 @@ func (ma *MetricsAggregator) InjectMetricsAggregator(pod *v1.Pod) error {
 		// If enableMetricAggregation is true, set it as the queue proxy metrics aggregation port.
 		podPromPort := constants.DefaultPodPrometheusPort
 		if enableMetricAggregation == "true" {
-			podPromPort = strconv.Itoa(constants.QueueProxyAggregatePrometheusMetricsPort)
+			podPromPort = strconv.Itoa(int(constants.QueueProxyAggregatePrometheusMetricsPort))
```
Comment (spolti) [inline pkg/webhook/admission/pod/metrics_aggregate_injector.go]: isn't better to keep the field as string?

File: pkg/constants/constants.go (hunk 1 above)
Comment (sivanantha321) [reply pkg/constants/constants.go]: Before it was int. kubernetes defines port as int32. This will lead to downcast and the lint will complain. Even if we change it to either string or int or int32,  the conversion is unavoidable. So i thought it is better to do a upcast rather than downcast and also the linter will be happy.

File: pkg/webhook/admission/pod/metrics_aggregate_injector.go (hunk 2 above)
Comment (sivanantha321) [reply pkg/webhook/admission/pod/metrics_aggregate_injector.go]: As explained above, it will lead to downcasting.

File: pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go [hunk 3]
```diff
@@ -94,12 +94,12 @@ func createHPA(componentMeta metav1.ObjectMeta,
 	componentExt *v1beta1.ComponentExtensionSpec) *autoscalingv2.HorizontalPodAutoscaler {
 	var minReplicas int32
 	if componentExt.MinReplicas == nil || (*componentExt.MinReplicas) < constants.DefaultMinReplicas {
-		minReplicas = int32(constants.DefaultMinReplicas)
+		minReplicas = int32(constants.DefaultMinReplicas) // #nosec G115
```
Comment (Jooho) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go]: I'm not sure if it's a good idea to add this comment every time I cast to int32 type. I think that ignoring warnings through comments can cause potential risks or oversights in the code. It's often better to fix the root cause of a warning than to suppress it.

I fixed it with the following method, what do you think?
https://github.com/kserve/kserve/pull/3972/files#diff-81ddbadfb415ccbb9c7af84f11668d1aa5e53c34025bf86d4702f16b4e42f045R249

Comment (sivanantha321) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go]: I think you are still doing the downcasting which will produce lint error.
```go
func ConvertStringToInt32(number int, defaultValue int) (int32, error) {
	if number > math.MaxInt32 {
		return int32(defaultValue), fmt.Errorf("the value exceeds int32 limit")
	}
	convertedNumber := int32(number) # Linter will not be happy
	return convertedNumber, nil
}
```

Comment (sivanantha321) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go]: I did something like this which didn't produce any lint errors
```go
func StringToInt32(number string) (int32, error) {
	converted, err := strconv.ParseInt(number, 10, 32)
	return int32(converted), err
}
```

**Comment by spolti** [comment]
@sivanantha321 are all the changes related with the golint-ci upgrade?

**Comment by sivanantha321** [comment]
> @sivanantha321 are all the changes related with the golint-ci upgrade?

Yes and it also enables lint for tests and fixes previously excluded lint errors as well.

**Review by terrytangyuan — DISMISSED** [review]
/lgtm
/approve

File: pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go [hunk 4]
```diff
@@ -44,30 +46,40 @@ type HPAReconciler struct {
...
+		if err != nil {
+			return metrics, err
+		}
 	} else {
 		utilization = constants.DefaultCPUUtilization
 	}
 
 	if componentExt.ScaleTarget != nil {
-		utilization = int32(*componentExt.ScaleTarget)
+		utilization, err = utils.StringToInt32(strconv.Itoa(*componentExt.ScaleTarget))
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go]: scaleTarget is defined as int, it is better to change the API type to int32.

File: pkg/controller/v1alpha1/localmodel/controller.go [hunk 5]
```diff
@@ -64,8 +64,8 @@ type LocalModelReconciler struct {
 var (
 	ownerKey         = ".metadata.controller"
 	localModelKey    = ".localmodel"
-	apiGVStr         = v1alpha1api.SchemeGroupVersion.String()
-	modelCacheCRName = "LocalModelCache"
+	apiGVStr         = v1alpha1.SchemeGroupVersion.String()
+	modelCacheCRName = "ClusterLocalModel"
```
Comment (yuzisun) [inline pkg/controller/v1alpha1/localmodel/controller.go]: CR name is changed from ClusterLocalModel to LocalModelcache

File: pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go (hunk 4 above)
Comment (sivanantha321) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go]: Done

File: pkg/controller/v1alpha1/localmodel/controller.go (hunk 5 above)
Comment (sivanantha321) [reply pkg/controller/v1alpha1/localmodel/controller.go]: Done

**Comment by spolti** [comment]
Hi @sivanantha321, is this PR ready for another round of review?

**Comment by sivanantha321** [comment]
> Hi @sivanantha321, is this PR ready for another round of review?

Yes. It needs rebase but it can be reviewed.

File: .github/PULL_REQUEST_TEMPLATE.md [hunk 6]
```diff
@@ -1,8 +1,9 @@
 <!--  Thanks for sending a pull request!  Here are some tips for you:
 1. If this is your first time, read our contributor guidelines https://www.kubeflow.org/docs/about/contributing/ and developer guide https://github.com/kserve/kserve/blob/master/docs/DEVELOPER_GUIDE.md
-2. If you want *faster* PR reviews, read how: https://git.k8s.io/community/contributors/guide/pull-requests.md#best-practices-for-faster-reviews
-3. Follow the instructions for writing a release note: https://git.k8s.io/community/contributors/guide/release-notes.md
-4. If the PR is unfinished, see how to mark it: https://git.k8s.io/community/contributors/guide/pull-requests.md#marking-unfinished-pull-requests
+2. Before raising a PR, please run `make go-lint` and `make py-fmt` to check the code style.
```
Comment (yuzisun) [inline .github/PULL_REQUEST_TEMPLATE.md:3]: @sivanantha321 We can follow ai gateway repo's precommit command, can be separate PR
https://github.com/envoyproxy/ai-gateway/blob/main/Makefile#L109

File: cmd/router/main_test.go [hunk 7]
```diff
@@ -472,11 +562,17 @@ func TestCallServiceWhen1HeaderToPropagate(t *testing.T) {
 	// Propagating only 1 header "Test-Header-Key"
 	headersToPropagate := []string{"Test-Header-Key"}
 	compiledHeaderPatterns, err = compilePatterns(headersToPropagate)
-	assert.Nil(t, err)
+	require.NoError(t, err)
 
 	res, _, err := callService(model1Url.String(), jsonBytes, headers)
+	if err != nil {
+		t.Fatalf("callService failed: %v", err)
+	}
```
Comment (yuzisun) [inline cmd/router/main_test.go:570]: We can use require.Error
