### PR TITLE
Fixed the panic nil pointer issue componentExt being nil

### LINKED ISSUE #4703: The annotation `serving.kserve.io/autoscalerClass: "external"` brings in the panic error in reconciling
/kind bug

**What steps did you take and what happened:**
Create an isvc with the annotation 
```
serving.kserve.io/autoscalerClass: "external"
serving.kserve.io/deploymentMode: "Standard"
```

It failed to launch the service with the following errors:

```
{"level":"error","ts":"2025-09-19T17:18:07Z","msg":"Observed a panic","controller":"inferenceservice","controllerGroup":"serving.kserve.io","controllerKind":"InferenceService","InferenceService":{"name":"a1utoscaling-llama-3-1-70b","namespace":"s-dsplatform"},"namespace":"s-dsplatform","name":"a1utoscaling-llama-3-1-70b","reconcileID":"7d22c0ff-a8d5-4aeb-86e7-8df25557ee4b","panic":"runtime error: invalid memory address or nil pointer dereference","panicGoValue":"\"invalid memory address or nil pointer dereference\"","stacktrace":"goroutine 505 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x32a6fb8, 0xc0021e4180}, {0x2840860, 0x4d90ac0})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.33.2/pkg/util/runtime/runtime.go:132 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:105 +0x112\npanic({0x2840860?, 0x4d90ac0?})\n\t/usr/local/go/src/runtime/panic.go:792 +0x132\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa.getHPAMetrics(0x0?)\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:64 +0x4a2\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa.createHPA({{0xc001895d40, 0x24}, {0x0, 0x0}, {0xc0012a2e00, 0xc}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:157 +0x6e\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa.NewHPAReconciler(...)\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:51\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler.createAutoscaler({0x32c1280, _}, _, {{0xc001895d40, 0x24}, {0x0, 0x0}, {0xc0012a2e00, 0xc}, {0x0, ...}, ...}, ...)\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go:94 +0x1e5\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler.NewAutoscalerReconciler({0x32c1280, _}, _, {{0xc001895d40, 0x24}, {0x0, 0x0}, {0xc0012a2e00, 0xc}, {0x0, ...}, ...}, ...)\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go:65 +0x7e\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/raw.NewRawKubeReconciler({_, _}, {_, _}, {_, _}, _, {{0xc001895d40, 0x24}, {0x0, ...}, ...}, ...)\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/raw/raw_kube_reconciler.go:93 +0x245\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components.(*Predictor).reconcileRawDeployment(_, {_, _}, _, {{0xc001895d40, 0x24}, {0x0, 0x0}, {0xc0012a2e00, 0xc}, ...}, ...)\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components/predictor.go:673 +0x105\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components.(*Predictor).Reconcile(0xc0017c8900, {0x32a6fb8, 0xc0021e4180}, 0xc0015b2008)\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components/predictor.go:186 +0x10c5\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile(0xc000c07320, {0x32a6fb8, 0xc0021e4180}, {{{0xc0012a2e00?, 0x2d970cb?}, {0xc001d520c0?, 0x100?}}})\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:255 +0x19ce\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc0021e40f0?, {0x32a6fb8?, 0xc0021e4180?}, {{{0xc0012a2e00?, 0x0?}, {0xc001d520c0?, 0x0?}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:116 +0xbf\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x32cb040, {0x32a6ff0, 0xc000ba0050}, {{{0xc0012a2e00, 0xc}, {0xc001d520c0, 0x1a}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:303 +0x3a5\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x32cb040, {0x32a6ff0, 0xc000ba0050})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:263 +0x20d\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:224 +0x85\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 306\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:220 +0x50d\n","stacktrace":"k8s.io/apimachinery/pkg/util/runtime.logPanic\n\t/go/pkg/mod/k8s.io/apimachinery@v0.33.2/pkg/util/runtime/runtime.go:142\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:105\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:792\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:262\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:925\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa.getHPAMetrics\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:64\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa.createHPA\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:157\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa.NewHPAReconciler\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:51\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler.createAutoscaler\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go:94\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler.NewAutoscalerReconciler\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go:65\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/raw.NewRawKubeReconciler\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/raw/raw_kube_reconciler.go:93\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components.(*Predictor).reconcileRawDeployment\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components/predictor.go:673\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components.(*Predictor).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components/predictor.go:186\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:255\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-09-19T17:18:07Z","msg":"Reconciler error","controller":"inferenceservice","controllerGroup":"serving.kserve.io","controllerKind":"InferenceService","InferenceService":{"name":"a1utoscaling-llama-3-1-70b","namespace":"s-dsplatform"},"namespace":"s-dsplatform","name":"a1utoscaling-llama-3-1-70b","reconcileID":"7d22c0ff-a8d5-4aeb-86e7-8df25557ee4b","error":"panic: runtime error: invalid memory address or nil pointer dereference [recovered]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:224"}
```

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by houshengbo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4703

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Review by spolti — COMMENTED** [review]
@israel-hdez may you take a look?

File: pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go [hunk 1]
```diff
@@ -90,8 +90,10 @@ func createAutoscaler(client client.Client,
 ) (Autoscaler, error) {
 	ac := getAutoscalerClass(componentMeta)
 	switch ac {
-	case constants.AutoscalerClassHPA, constants.AutoscalerClassExternal, constants.AutoscalerClassNone:
+	case constants.AutoscalerClassHPA:
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go]: I think it was using hpa reconciler to cover the case that inference service is updated from using HPA to none or external, so you need the logic to delete the underlying hpa.

Comment (houshengbo) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go]: Just revert the changes for constants.AutoscalerClassExternal, and constants.AutoscalerClassNone.

**Review by yuzisun — APPROVED** [review]
