### PR TITLE
fix(inferenceservice): skip VS if Istio CRD missing

### LINKED ISSUE #4984: IngressReconciler fails when Istio VirtualService CRD is not installed
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
# Steps to Reproduce
- Deploy KServe in a cluster without Istio installed (e.g., using Kourier as the network layer)
- Create an InferenceService
- Observe reconciliation errors in the controller logs

# Summary
When the Istio VirtualService CRD is not installed in the cluster (e.g., when using Kourier as the network layer), the IngressReconciler.reconcileVirtualService method fails with errors, causing the entire reconciliation process to terminate abnormally.

# Environment
- KServe Version: main branch
- Kubernetes Version: Any
- Network Layer: Non-Istio (e.g., Kourier)

# Problem Description
The `InferenceServiceReconciler` checks for `VirtualService` CRD availability in 
`SetupWithManager`:

```
vsFound, err := utils.IsCrdAvailable(r.ClientConfig, istioclientv1beta1.SchemeGroupVersion.String(), constants.IstioVirtualServiceKind)
```
However, this information is not passed to the `IngressReconciler`. When reconcileVirtualService is called, it attempts to perform `VirtualService` operations (Get/Create/Update/Delete) without checking if the CRD exists, causing runtime errors.

# Expected Behavior

The `IngressReconciler` should gracefully handle the absence of Istio `VirtualService` CRD:

- Skip `VirtualService` reconciliation when the CRD is not available
- Continue with other ingress reconciliation tasks (ExternalService, URL/Address setup)
- No errors or warnings should be logged

# Actual Behavior
The reconciler attempts to operate on VirtualService resources, causing errors that terminate the reconciliation process.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: X
- Knative Version: 1.19 (with kourier)
- KServe Version: 0.16.0
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Siva-Sainath**
This fixes #4984 where KServe InferenceServiceReconciler would fail to reconcile when Istio VirtualService CRD is not installed in the cluster

Ex: when using Kourier as the network layer

Changes:
- Add isVirtualServiceAvailable field to IngressReconciler to track VirtualService CRD availability
- Pass vsFound flag from InferenceServiceReconciler to IngressReconciler
- Guard reconcileVirtualService() with CRD availability check

When VirtualService CRD is not available, reconciliation gracefully skips VirtualService operations and continues with other ingress tasks, allowing successful InferenceService deployment on non-Istio clusters.

Tests:
Test A [ ]
(Unit tests - fast): [go test ./pkg/controller/v1beta1/inferenceservice/reconcilers/ingress -v](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) — PASS (includes skip test).
Test B [ ]
(Integration - KinD + Kourier / no-Istio): validated locally by running the manager against a KinD cluster without Istio VirtualService CRD; manager logs show it skips watching VirtualService resources and no reconciliation errors occur.

Docs

[COMMON_ISSUES_AND_SOLUTIONS.md](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html): added troubleshooting entry.
[OPENSHIFT_GUIDE.md](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html): added note in the Kourier section.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the [documentation](https://github.com/kserve/website)?

```release-note
NONE

```

### CODE REVIEW

File: pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go [hunk 1]
```diff
@@ -231,6 +235,12 @@ func getHostBasedServiceUrl(isvc *v1beta1.InferenceService, config *v1beta1.Ingr
 func (ir *IngressReconciler) reconcileVirtualService(ctx context.Context, isvc *v1beta1.InferenceService) error {
 	disableIstioVirtualHost := ir.ingressConfig.DisableIstioVirtualHost
 
+	// If Istio VirtualService CRD is not present in the cluster, gracefully skip VirtualService reconciliation.
```
Comment (sivanantha321) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go:240]: isn't it enough to check if the `disableIstioVirtualHost` is true and skip the virtualservice reconcilation ?

Comment (spolti) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go:240]: There might be scenarios where the user configures it to true, but no CRD is available, in such scenarios, wouldn't it be better have events notifying the user?

File: docs/COMMON_ISSUES_AND_SOLUTIONS.md [hunk 2]
```diff
@@ -54,3 +54,18 @@ Issue Template
 - Author: Jooho Lee/jlee@redhat.com
 - Date: 2024-08-19
 - Related Issues/PRs: X
+
+---
+### VirtualService reconciliation attempts when Istio is not installed
+- Summary: KServe may attempt to reconcile Istio `VirtualService` resources even when the Istio VirtualService CRD is not available, causing reconciliation errors and failed deployments on non-Istio clusters (e.g., Kourier).
+- Symptoms:
```
Comment (spolti) [inline docs/COMMON_ISSUES_AND_SOLUTIONS.md]: Can we add an event recorder? Or add something in the isvc status?

File: pkg/controller/v1beta1/inferenceservice/controller.go [hunk 3]
```diff
@@ -343,7 +345,7 @@ func (r *InferenceServiceReconciler) Reconcile(ctx context.Context, req ctrl.Req
 			}
 		}
 	} else {
-		reconciler := ingress.NewIngressReconciler(r.Client, r.Clientset, r.Scheme, ingressConfig, isvcConfig)
+		reconciler := ingress.NewIngressReconciler(r.Client, r.Clientset, r.Scheme, ingressConfig, isvcConfig, r.VirtualServiceAvailable)
```
Comment (spolti) [inline pkg/controller/v1beta1/inferenceservice/controller.go]: Looks like this PR needs to be rebased, the reconciles were changed as part of #4922

**Comment by Siva-Sainath** [comment]
@sivanantha321 @spolti thank you for reviewing my PR, I have made the changes as requested and am asking for any one of the maintainers to approve workflows so that the tests can run for my latest commit

File: pkg/controller/v1beta1/inferenceservice/controller.go (hunk 3 above)
Comment (Siva-Sainath) [reply pkg/controller/v1beta1/inferenceservice/controller.go]: I have rebased the PR thank you

**Review by sivanantha321 — APPROVED** [review]

File: pkg/controller/v1beta1/inferenceservice/controller.go [hunk 4]
```diff
@@ -322,14 +324,23 @@ func (r *InferenceServiceReconciler) Reconcile(ctx context.Context, req ctrl.Req
 	// Reconcile ingress using factory
 	factory := reconcilers.NewReconcilerFactory()
 
+	// Notify user when the Istio VirtualService CRD is not present but
+	// Istio virtual host is expected (disableIstioVirtualHost == false).
+	// This makes the skip visible instead of silent.
+	if !r.VirtualServiceAvailable && !ingressConfig.DisableIstioVirtualHost {
+		r.Recorder.Event(isvc, corev1.EventTypeWarning, "VirtualServiceCRDNotFound",
```
Comment (sivanantha321) [inline pkg/controller/v1beta1/inferenceservice/controller.go:333]: Can we also log this as error ?

Comment (Siva-Sainath) [reply pkg/controller/v1beta1/inferenceservice/controller.go:333]: yes sure @sivanantha321 will make sure its logged as a error

**Comment by sivanantha321** [comment]
Thanks for addressing this!

**Comment by Siva-Sainath** [comment]
Thank you for the valuable feedback and support @sivanantha321
