### PR TITLE
fix: hpa scale up failed, when using rawdeployment

### LINKED ISSUE #2278: Hpa scale up failed when in rawdeployment
/kind bug
**What steps did you take and what happened:**
Deploy `isvc` in `RawDeployment` mode, add `annotation`:
```
annotations:
    serving.kserve.io/deploymentMode: "RawDeployment"
    serving.kserve.io/autoscalerClass: "hpa"
    serving.kserve.io/metrics: "cpu"
    serving.kserve.io/targetUtilizationPercentage: "30"
```
then, start load testing, and watching the behavior of hpa controller.

**What did you expect to happen:**
increase the pod num

**Anything else you would like to add:**
By watching the log of `kserve-manager`, we can get the deployment of the target `isvc` prints `check_result=1`, that means the deployment object is updated, after debugging this, we found that: when `isvc` is scaled up, the `replicas` of deployment is changed, and `kserve-manager` got this as an unexpected update, so reset the deployment to last version, this cause the failed of scaling.

### PR DESCRIPTION
**Pull request by Iamlovingit**
Signed-off-by: iamlovingit <bitfrog@163.com>

**What this PR does / why we need it**:
Fixes #2278 #2269 

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Test result:
* **Create a `isvc` service**
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "custom-simple"
  namespace: "cqs"
  annotations:
    serving.kserve.io/deploymentMode: "RawDeployment"
    serving.kserve.io/autoscalerClass: "hpa"
    serving.kserve.io/metrics: "cpu"
    serving.kserve.io/targetUtilizationPercentage: "30"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 10
    containers:
    - image: iamlovingit/bgtest:latest
      name: custom
      ports:
      - containerPort: 8080
        protocol: TCP
```
```
kubectl get all -n cqs                                                                                                                                                                              Tue Jun 28 20:15:40 2022

NAME                                                   READY   STATUS    RESTARTS   AGE
pod/custom-simple-predictor-default-776cb967f4-8897f   1/1     Running   0          18s

NAME                                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/custom-simple-predictor-default   ClusterIP   10.103.124.101   <none>        80/TCP    19s

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/custom-simple-predictor-default   1/1     1            1           19s

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/custom-simple-predictor-default-776cb967f4   1         1         1       19s

NAME                                                                  REFERENCE                                    TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/custom-simple-predictor-default   Deployment/custom-simple-predictor-default   <unknown>/30%   1         10        1          19s
```
* **Starting load test**
```
hey -m POST -c 10 -z 5m http://10.103.124.101/single
```

* **Watch the behavior of scaling**
```shell
kubectl get all -n cqs                                                                                                                                                                              Tue Jun 28 20:23:17 2022

NAME                                                   READY   STATUS     RESTARTS   AGE
pod/custom-simple-predictor-default-776cb967f4-7bf6b   1/1     Running    0          17s
pod/custom-simple-predictor-default-776cb967f4-8897f   1/1     Running    0          7m56s
pod/custom-simple-predictor-default-776cb967f4-wj6wt   0/1     Init:0/1   0          2s

NAME                                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/custom-simple-predictor-default   ClusterIP   10.103.124.101   <none>        80/TCP    7m57s

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/custom-simple-predictor-default   2/3     3            2           7m57s

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/custom-simple-predictor-default-776cb967f4   3         3         2       7m57s

NAME                                                                  REFERENCE                                    TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/custom-simple-predictor-default   Deployment/custom-simple-predictor-default   87%/30%   1         10        2          7m57s
```
The description of `HPA` after scaled up
```
kubectl describe hpa -n cqs
Name:                                                  custom-simple-predictor-default
Namespace:                                             cqs
Labels:                                                app=isvc.custom-simple-predictor-default
                                                       component=predictor
                                                       serving.kserve.io/inferenceservice=custom-simple
Annotations:                                           serving.kserve.io/autoscalerClass: hpa
                                                       serving.kserve.io/deploymentMode: RawDeployment
                                                       serving.kserve.io/metrics: cpu
                                                       serving.kserve.io/targetUtilizationPercentage: 30
CreationTimestamp:                                     Tue, 28 Jun 2022 20:15:21 +0800
Reference:                                             Deployment/custom-simple-predictor-default
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  28% (280m) / 30%
Min replicas:                                          1
Max replicas:                                          10
Behavior:
  Scale Up:
    Stabilization Window: 0 seconds
    Select Policy: Max
    Policies:
      - Type: Pods     Value: 4    Period: 15 seconds
      - Type: Percent  Value: 100  Period: 15 seconds
  Scale Down:
    Select Policy: Max
    Policies:
      - Type: Percent  Value: 100  Period: 15 seconds
Deployment pods:       3 current / 3 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:
  Type     Reason                        Age                   From                       Message
  ----     ------                        ----                  ----                       -------
  Warning  FailedGetResourceMetric       8m20s (x4 over 9m7s)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  8m20s (x4 over 9m7s)  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Normal   SuccessfulRescale             105s                  horizontal-pod-autoscaler  New size: 2; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             89s                   horizontal-pod-autoscaler  New size: 3; reason: cpu resource utilization (percentage of request) above target
```
* **Stop load test and watching the behavior of scaling down**
```
kubectl get all -n cqs                                                                                                                                                                              Tue Jun 28 20:31:31 2022

NAME                                                   READY   STATUS        RESTARTS   AGE
pod/custom-simple-predictor-default-776cb967f4-7bf6b   0/1     Terminating   0          8m30s
pod/custom-simple-predictor-default-776cb967f4-8897f   1/1     Running       0          16m

NAME                                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/custom-simple-predictor-default   ClusterIP   10.103.124.101   <none>        80/TCP    16m

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/custom-simple-predictor-default   1/1     1            1           16m

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/custom-simple-predictor-default-776cb967f4   1         1         1       16m

NAME                                                                  REFERENCE                                    TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/custom-simple-predictor-default   Deployment/custom-simple-predictor-default   0%/30%    1         10        2          16m
```
The description of `HPA` after scaled down
```
kubectl describe hpa -n cqs
Name:                                                  custom-simple-predictor-default
Namespace:                                             cqs
Labels:                                                app=isvc.custom-simple-predictor-default
                                                       component=predictor
                                                       serving.kserve.io/inferenceservice=custom-simple
Annotations:                                           serving.kserve.io/autoscalerClass: hpa
                                                       serving.kserve.io/deploymentMode: RawDeployment
                                                       serving.kserve.io/metrics: cpu
                                                       serving.kserve.io/targetUtilizationPercentage: 30
CreationTimestamp:                                     Tue, 28 Jun 2022 20:15:21 +0800
Reference:                                             Deployment/custom-simple-predictor-default
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  0% (1m) / 30%
Min replicas:                                          1
Max replicas:                                          10
Behavior:
  Scale Up:
    Stabilization Window: 0 seconds
    Select Policy: Max
    Policies:
      - Type: Pods     Value: 4    Period: 15 seconds
      - Type: Percent  Value: 100  Period: 15 seconds
  Scale Down:
    Select Policy: Max
    Policies:
      - Type: Percent  Value: 100  Period: 15 seconds
Deployment pods:       1 current / 1 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    TooFewReplicas    the desired replica count is less than the minimum replica count
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedGetResourceMetric       16m (x4 over 17m)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  16m (x4 over 17m)  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Normal   SuccessfulRescale             10m                horizontal-pod-autoscaler  New size: 2; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             9m47s              horizontal-pod-autoscaler  New size: 3; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             108s               horizontal-pod-autoscaler  New size: 2; reason: All metrics below target
  Normal   SuccessfulRescale             93s                horizontal-pod-autoscaler  New size: 1; reason: All metrics below target
```

* **Update the `minReplicas` and `maxReplicas` of `isvc` by user**
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "custom-simple"
  namespace: "cqs"
  annotations:
    serving.kserve.io/deploymentMode: "RawDeployment"
    serving.kserve.io/autoscalerClass: "hpa"
    serving.kserve.io/metrics: "cpu"
    serving.kserve.io/targetUtilizationPercentage: "30"
spec:
  predictor:
    minReplicas: 3
    maxReplicas: 15
    containers:
    - image: iamlovingit/bgtest:latest
      name: custom
      ports:
      - containerPort: 8080
        protocol: TCP
``` 
**Result after updated:**
```
kubectl get all -n cqs                                                                                                                                                                              Tue Jun 28 20:38:14 2022

NAME                                                   READY   STATUS    RESTARTS   AGE
pod/custom-simple-predictor-default-776cb967f4-5blkz   1/1     Running   0          15s
pod/custom-simple-predictor-default-776cb967f4-8897f   1/1     Running   0          22m
pod/custom-simple-predictor-default-776cb967f4-x77fr   1/1     Running   0          15s

NAME                                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/custom-simple-predictor-default   ClusterIP   10.103.124.101   <none>        80/TCP    22m

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/custom-simple-predictor-default   3/3     3            3           22m

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/custom-simple-predictor-default-776cb967f4   3         3         3       22m

NAME                                                                  REFERENCE                                    TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/custom-simple-predictor-default   Deployment/custom-simple-predictor-default   <unknown>/30%   3         15        1          22m
```

### CODE REVIEW

File: pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go [hunk 1]
```diff
@@ -106,13 +107,19 @@ func (r *DeploymentReconciler) checkDeploymentExist(client client.Client) (const
...
 	}
+
+	diff, err := kmp.SafeDiff(r.Deployment.Spec, existingDeployment.Spec)
+	log.Info("Deployment Updated", "Diff", diff, "err", err)
+
 	return constants.CheckResultUpdate, existingDeployment, nil
 }
 
-func semanticDeploymentEquals(desired, existing *appsv1.Deployment) bool {
+func semanticDeploymentEquals(desired, existing appsv1.Deployment) bool {
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go]: Why this can't be passed as pointer?

File: pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go [hunk 2]
```diff
@@ -106,13 +107,19 @@ func (r *DeploymentReconciler) checkDeploymentExist(client client.Client) (const
...
+	//for HPA scaling, we should ignore Replicas of Deployment
+	*desired.Spec.Replicas = *existing.Spec.Replicas
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go]: probably not a good idea to mutate the field in an equal function

File: pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go [hunk 3]
```diff
@@ -106,13 +107,19 @@ func (r *DeploymentReconciler) checkDeploymentExist(client client.Client) (const
 		return constants.CheckResultUnknown, nil, err
 	}
 	//existed, check equivalence
-	if semanticDeploymentEquals(r.Deployment, existingDeployment) {
+	if semanticDeploymentEquals(*r.Deployment, *existingDeployment) {
 		return constants.CheckResultExisted, existingDeployment, nil
 	}
+
+	diff, err := kmp.SafeDiff(r.Deployment.Spec, existingDeployment.Spec)
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go]: we can use `SafeDiff` directly on line 110, the function might have option to exclude the replica field.

Comment (yuzisun) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go]: what happens when user actually updates the deployment replica?

File: pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go (hunk 2 above)
Comment (yuzisun) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go]: according to https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#migrating-deployments-and-statefulsets-to-horizontal-autoscaling we should not set replica field if HPA is used.

Comment (Iamlovingit) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go]: good idea, now we removed `Replicas` from the `Deployment Rconciler`, and use safe diff + ignoreFields for implementation.

File: pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go (hunk 3 above)
Comment (Iamlovingit) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go]: > what happens when user actually updates the deployment replica?

If user modfiys the `isvc minReplicas`, the `hpa` will be updated, and then `hpa` will scale up/down the num of `Deployment`.

Comment (yuzisun) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go]: @Iamlovingit I think this code can be simplified to the following on line 99 and remove line 103
```go
	ignoreFields := cmpopts.IgnoreFields(appsv1.DeploymentSpec{}, "Replicas")
	if diff, err := kmp.SafeDiff(r.Deployment.Spec, existingDeployment.Spec, ignoreFields); err != nil || diff == "" {
		return constants.CheckResultExisted, existingDeployment, err
	}
```

**Comment by yuzisun** [comment]
Thanks @Iamlovingit !

/lgtm
/approve
