### PR TITLE
Fix model agent settings when deployed as raw deployment

### LINKED ISSUE #1857: MMS agent fails to start in raw deployment mode due to dependency on Knative queue-proxy env vars
/kind bug

**What steps did you take and what happened:**

Ensure default deployment mode is set to `RawDeployment` in the inferenceservice-config config map.

Create a multi-model inference service:
```
kubectl apply -f docs/samples/multimodelserving/triton/multi_model_triton.yaml 
```
The agent fails to start due to missing environment variables.

Agent logs:
```
required key CONTAINER_CONCURRENCY missing value
```

**What did you expect to happen:**

The agent should start up without errors.

**Anything else you would like to add:**

The environment variables are added by the agent injector [here](https://github.com/kserve/kserve/blob/638fff64d833e3c5b378b16eda12d5e131417541/pkg/webhook/admission/pod/agent_injector.go#L224).

**Environment:**

- Istio Version: N/A
- Knative Version: N/A
- KFServing Version: [master](https://github.com/kserve/kserve/tree/829db48f25baffba9c26771716e68629302af7c5)
- Kubeflow version: N/A
- Kfdef: N/A
- Minikube version: v1.23.2
- Kubernetes version: v1.20.11
- OS: macOS 11.5.2

### PR DESCRIPTION
**Pull request by andyi2it**
**What this PR does / why we need it**:
Raw deployment mode in kserve does not require knative to be installed. However, the environment variables are set from queue proxy. Since  knative is not present, mms agent throws error for missing fields.
Made changes to get readiness probe from pod spec and use it as env to agent

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1857 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/webhook/admission/pod/agent_injector_test.go [hunk 1]
```diff
@@ -122,7 +122,7 @@ func TestAgentInjector(t *testing.T) {
 								},
 							},
 							Args: []string{"--enable-puller", "--config-dir", "/mnt/configs", "--model-dir", "/mnt/models"},
-							Env:  []v1.EnvVar{},
+							Env:  []v1.EnvVar{{Name: "SERVING_READINESS_PROBE", Value: "null"}},
```
Comment (yuzisun) [inline pkg/webhook/admission/pod/agent_injector_test.go]: Add the readiness probe in the test input so we can verify here?

Comment (andyi2it) [reply pkg/webhook/admission/pod/agent_injector_test.go]: Sorry Dan, am not sure if I understand you correctly, will ping you in chat.

**Comment by yuzisun** [comment]
Thanks @andyi2it !
/lgtm
/approve
