### PR TITLE
Fix raw deployment status.address.url displays wrong url

### LINKED ISSUE #2829: Inferenceservice address.url displays wrong url in raw deployment
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Inference service status.address.url points to http://\<isvc-name\>.\<namespace\>.svc.cluster.local which is invalid.

**What did you expect to happen:**
It should point to either http://\<isvc-name\>-predictor.\<namespace\>.svc.cluster.local or http://\<isvc-name\>-transformer.\<namespace\>.svc.cluster.local

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
```yaml
status:
  address:
    url: http://mnist.default.svc.cluster.local/
  components:
    predictor:
      latestCreatedRevision: '1'
      url: http://mnist-predictor-default.example.com/
    transformer:
      latestCreatedRevision: '1'
      url: http://mnist-transformer-default.example.com/
  conditions:
    - lastTransitionTime: '2023-04-18T05:54:19Z'
      status: 'True'
      type: IngressReady
    - lastTransitionTime: '2023-04-18T05:54:11Z'
      status: 'True'
      type: PredictorReady
    - lastTransitionTime: '2023-04-18T05:54:19Z'
      status: 'True'
      type: Ready
    - lastTransitionTime: '2023-04-18T05:54:19Z'
      severity: Info
      status: 'True'
      type: TransformerReady
  modelStatus:
    copies:
      failedCopies: 0
      totalCopies: 1
    states:
      activeModelState: Loaded
      targetModelState: Loaded
    transitionStatus: UpToDate
  observedGeneration: 1
  url: http://mnist-default.example.com/
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.16.2
- Knative Version: 1.9.0
- KServe Version: master
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): 1.24.12
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by sivanantha321**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2829 #2587 

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

File: pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go [hunk 1]
```diff
@@ -299,15 +313,23 @@ func (r *RawIngressReconciler) Reconcile(isvc *v1beta1api.InferenceService) erro
...
 		return err
 	}
+
+	// Check if existing service name has default suffix
+	useDefaultSuffix := false
+	existingService := &corev1.Service{}
+	err = r.client.Get(context.TODO(), types.NamespacedName{Name: constants.DefaultTransformerServiceName(isvc.Name), Namespace: isvc.Namespace}, existingService)
+	if err == nil {
+		useDefaultSuffix = true
+	}
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go]: Wrap this logic in `getRawServiceHost` ? also transformer is optional component

Comment (sivanantha321) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go]: done
