### PR TITLE
Fix runtime not found for triton due to wrong default protocolVersion

### LINKED ISSUE #3176: Runtime not found for triton if protocolVersion is not specified
/kind bug

**What steps did you take and what happened:**
Getting runtime not found error for triton if protocolVersion is not specified in the isvc resource. This due to the fact that default protocolVersion is set to `v1` instead of `v2`.

**What did you expect to happen:**
The protocolVersion should be set to `v2` for triton if protocolVersion is not specified. 

**What's the InferenceService yaml:**
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    identities.bloomberg.com/bcs: dsplatform-bcs-gen
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{"identities.bloomberg.com/bcs":"dsplatform-bcs-gen"},"name":"inferno-triton","namespace":"s-dsplatform"},"spec":{"predictor":{"model":{"modelFormat":{"name":"triton"},"name":"","resources":{"limits":{"cpu":"1","memory":"4Gi"},"requests":{"cpu":"1","memory":"1Gi"}},"runtimeVersion":"22.07-py3","storageUri":"s3://kserve-workshop/models/triton"}}}}
  creationTimestamp: "2023-10-07T00:11:14Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 1
  name: inferno-triton
  namespace: s-dsplatform
  resourceVersion: "503060720"
  uid: 2d9a45e0-bdfd-4684-8424-f90414d7a346
spec:
  predictor:
    model:
      modelFormat:
        name: triton
      name: ""
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 1Gi
      runtimeVersion: 22.07-py3
      storageUri: <storage-uri>
status:
  modelStatus:
    lastFailureInfo:
      message: No runtime found to support specified framework/version
      reason: NoSupportingRuntime
    states:
      activeModelState: ""
      targetModelState: FailedToLoad
    transitionStatus: InvalidSpec
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by sivanantha321**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3176

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
Fix runtime not found for triton due to wrong default protocolVersion if protcolVersion is not specified in the isvc resource
```

### CODE REVIEW

File: pkg/apis/serving/v1beta1/inference_service_defaults.go [hunk 1]
```diff
@@ -145,6 +145,14 @@ func (isvc *InferenceService) setPredictorModelDefaults() {
 	case isvc.Spec.Predictor.Paddle != nil:
 		isvc.assignPaddleRuntime()
 	}
+
+	if isvc.Spec.Predictor.Model != nil && isvc.Spec.Predictor.Model.ProtocolVersion == nil {
```
Comment (yuzisun) [inline pkg/apis/serving/v1beta1/inference_service_defaults.go:149]: Wondering why this logic is not executed in SetTritonDefaults?

Comment (sivanantha321) [reply pkg/apis/serving/v1beta1/inference_service_defaults.go:149]: That function is only called after selecting the runtime. https://github.com/kserve/kserve/blob/294a10495b6b5cda9c64d3e1573b60aec62aceb9/pkg/controller/v1beta1/inferenceservice/components/predictor.go#L156
