### PR TITLE
Fix: Unexpected Panic in Inference graph when it fails to create http request

### LINKED ISSUE #3078: Unexpected Panic in Inference graph
/kind bug

**What steps did you take and what happened:**
I followed this(https://github.com/kserve/kserve/blob/master/docs/samples/graph/README.md) steps to test the Inference Graph with switch Node, and the graph I created is successfully running:

```NAME                                                   READY   STATUS    RESTARTS   AGE
model-switch-00001-deployment-7888fbb487-2ksm5         2/2     Running   0          5h41m
single-1-predictor-00001-deployment-5b87997486-5lkjq   2/2     Running   0          5h41m
single-2-predictor-00001-deployment-758bdbf7bd-hz4tg   2/2     Running   0          5h41m
single-3-predictor-00001-deployment-5f4cb65665-pbcgg   2/2     Running   0          5h41m
```

Since I don't have DNS setup, I used port forwarding:

`sudo kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:80`

and executed the following commands:
```
export IG_HOSTNAME=$(sudo kubectl get ig model-switch -o jsonpath='{.status.url}' | cut -d "/" -f 3)
curl -v -H "Host: ${IG_HOSTNAME}" -H "Content-type: application/json" http://localhost:8080 -d '{"source":"client1","instances":[{"name":"blue","intval":0,"strval":"kserve"},{"name":"green","intval":1,"strval":"1red-server1"}]}'
```
However, I received the following result:
```
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST / HTTP/1.1
> Host: model-switch.default.example.com
> User-Agent: curl/7.81.0
> Accept: */*
> Content-type: application/json
> Content-Length: 131
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 502 Bad Gateway
< content-length: 4
< content-type: text/plain; charset=utf-8
< date: Wed, 16 Aug 2023 14:25:01 GMT
< x-content-type-options: nosniff
< x-envoy-upstream-service-time: 2
< server: istio-envoy
<
EOF
* Connection #0 to host localhost left intact
```
After dig the issue bit, we found two possible errors make this 502 response:

1. The URL specified in the switch.yaml is incorrect which needs to be modified accordingly
```
- serviceUrl: http://single-1.default.{$your-domain}/switch
  condition: "[@this].#(source==client)" #object matching
- serviceUrl: http://single-2.default.{$your-domain}/switch
  condition: "instances.#(intval>10)" #array matching
- serviceUrl: http://single-3.default.{$your-domain}/switch 
  condition: "instances.#(strval%*red-server*)" #pattern matching
```

2. Server went to panic as the stack traced listed below:
```
Defaulted container "user-container" out of: user-container, queue-proxy
 
{"level":"info","ts":"2023-08-16T09:34:30Z","logger":"InferenceGraphRouter","msg":"Entering callService","url":"http://single-3.default.{$your-domain}/switch"}
 
{"level":"info","ts":"2023-08-16T09:34:30Z","logger":"InferenceGraphRouter","msg":"elapsed time","step":"http://single-3.default.{$your-domain}/switch","time":0.000170568}
 
{"level":"info","ts":"2023-08-16T09:34:30Z","logger":"InferenceGraphRouter","msg":"elapsed time","node":"root","time":0.000230312}
 
2023/08/16 09:34:30 http: panic serving 127.0.0.1:45014: runtime error: invalid memory address or nil pointer dereference
 
goroutine 14 [running]:
 
net/http.(*conn).serve.func1()
 
	/usr/local/go/src/net/http/server.go:1854 +0xbf
 
panic({0x173b740, 0x29d4dc0})
 
	/usr/local/go/src/runtime/panic.go:890 +0x263
 
main.callService({0xc000291a10, 0x2d}, {0xc0000d2000, 0x83, 0x200}, 0x33?)
 
	/go/src/github.com/kserve/kserve/cmd/router/main.go:55 +0x2bd
 
main.executeStep(0xc000285a00?, {0xc0006b8b40, {0x0, 0x0, {0x0, 0x0, 0x0}}, 0x0}, {0xc0000d2000, 0x83, ...}, ...)
 
	/go/src/github.com/kserve/kserve/cmd/router/main.go:183 +0xe6
 
main.routeStep({0x193ba84, 0x4}, {0xc0006b8b40, {0x0, 0x0, {0x0, 0x0, 0x0}}, 0x0}, {0xc0000d2000, ...}, ...)
 
	/go/src/github.com/kserve/kserve/cmd/router/main.go:113 +0x37d
 
main.graphHandler({0x1d7c0e0, 0xc00018e380}, 0xc000040900)
 
	/go/src/github.com/kserve/kserve/cmd/router/main.go:190 +0x10e
 
net/http.HandlerFunc.ServeHTTP(0xc00018e380?, {0x1d7c0e0?, 0xc00018e380?}, 0xc00029a1c4?)
 
	/usr/local/go/src/net/http/server.go:2122 +0x2f
 
net/http.(*ServeMux).ServeHTTP(0x0?, {0x1d7c0e0, 0xc00018e380}, 0xc000040900)
 
	/usr/local/go/src/net/http/server.go:2500 +0x149
 
net/http.serverHandler.ServeHTTP({0x1d6d9d0?}, {0x1d7c0e0, 0xc00018e380}, 0xc000040900)
 
	/usr/local/go/src/net/http/server.go:2936 +0x316
 
net/http.(*conn).serve(0xc0000c62d0, {0x1d7cb50, 0xc0006b8cf0})
 
	/usr/local/go/src/net/http/server.go:1995 +0x612
 
created by net/http.(*Server).Serve
 
	/usr/local/go/src/net/http/server.go:3089 +0x5ed
 
{"level":"info","ts":"2023-08-16T14:09:44Z","logger":"InferenceGraphRouter","msg":"Entering callService","url":"http://single-3.default.{$your-domain}/switch"}
 
{"level":"info","ts":"2023-08-16T14:09:44Z","logger":"InferenceGraphRouter","msg":"elapsed time","step":"http://single-3.default.{$your-domain}/switch","time":0.000062813}
 
{"level":"info","ts":"2023-08-16T14:09:44Z","logger":"InferenceGraphRouter","msg":"elapsed time","node":"root","time":0.00010731}
 
2023/08/16 14:09:44 http: panic serving 127.0.0.1:50466: runtime error: invalid memory address or nil pointer dereference
 
goroutine 1721 [running]:
 
net/http.(*conn).serve.func1()
 
	/usr/local/go/src/net/http/server.go:1854 +0xbf
 
panic({0x173b740, 0x29d4dc0})
 
	/usr/local/go/src/runtime/panic.go:890 +0x263
 
main.callService({0xc000291a10, 0x2d}, {0xc000384400, 0x83, 0x200}, 0x33?)
 
	/go/src/github.com/kserve/kserve/cmd/router/main.go:55 +0x2bd
 
main.executeStep(0xc000285a00?, {0xc0006b8b40, {0x0, 0x0, {0x0, 0x0, 0x0}}, 0x0}, {0xc000384400, 0x83, ...}, ...)
 
	/go/src/github.com/kserve/kserve/cmd/router/main.go:183 +0xe6
 
main.routeStep({0x193ba84, 0x4}, {0xc0006b8b40, {0x0, 0x0, {0x0, 0x0, 0x0}}, 0x0}, {0xc000384400, ...}, ...)
 
	/go/src/github.com/kserve/kserve/cmd/router/main.go:113 +0x37d
 
main.graphHandler({0x1d7c0e0, 0xc00018e380}, 0xc000598500)
 
	/go/src/github.com/kserve/kserve/cmd/router/main.go:190 +0x10e
 
net/http.HandlerFunc.ServeHTTP(0xc00018e380?, {0x1d7c0e0?, 0xc00018e380?}, 0x194785d?)
 
	/usr/local/go/src/net/http/server.go:2122 +0x2f
 
net/http.(*ServeMux).ServeHTTP(0x0?, {0x1d7c0e0, 0xc00018e380}, 0xc000598500)
 
	/usr/local/go/src/net/http/server.go:2500 +0x149
 
net/http.serverHandler.ServeHTTP({0x1d6d9d0?}, {0x1d7c0e0, 0xc00018e380}, 0xc000598500)
```

We don't think the panic should happened in this situation, seems the errors are not handled  properly as listed here:

(https://github.com/kserve/kserve/blob/master/cmd/router/main.go#L47)
```
func callService(serviceUrl string, input []byte, headers http.Header) ([]byte, error) {
	defer timeTrack(time.Now(), "step", serviceUrl)
	log.Info("Entering callService", "url", serviceUrl)
	req, err := http.NewRequest("POST", serviceUrl, bytes.NewBuffer(input))
	for _, h := range headersToPropagate {
		if values, ok := headers[h]; ok {
			for _, v := range values {
				req.Header.Add(h, v)
			}
		}
	}
```
**What did you expect to happen:**

The server should return 4xx errors instead of 5xx erros

### PR DESCRIPTION
**Pull request by HAO2167**
**What this PR does / why we need it**:
Add  Error handling
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3078

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:
Only add  Error handling , no need test plan.

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by rachitchauhan43** [comment]
This is already being handled here https://github.com/kserve/kserve/pull/3079
Returning error here won't fix the IG's response code. It needed but more handling that as been added here https://github.com/kserve/kserve/pull/3039

**Comment by hsinhoyeh** [comment]
> This is already being handled here #3079 Returning error here won't fix the IG's response code. It needed but more handling that as been added here #3039

@rachitchauhan43 I checked on your PR #3039, and the critical part is STILL not handled as well.
the root cause of issue #3078 is when the serviceUrl is not legit,  NewRequest would throw an error (as specified here https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/net/http/request.go;l=856) and that error should be properly handled.

File: cmd/router/main.go [hunk 1]
```diff
@@ -45,6 +45,10 @@ func callService(serviceUrl string, input []byte, headers http.Header) ([]byte,
 	defer timeTrack(time.Now(), "step", serviceUrl)
 	log.Info("Entering callService", "url", serviceUrl)
 	req, err := http.NewRequest("POST", serviceUrl, bytes.NewBuffer(input))
+	if err != nil {
+		log.Error(err, "An error has occurred from service", "service", serviceUrl)
```
Comment (rachitchauhan43) [inline cmd/router/main.go]:
```suggestion
		log.Error(err, "An error occurred while preparing request object with serviceUrl.", "serviceUrl", serviceUrl)
```

**Review by rachitchauhan43 — CHANGES_REQUESTED** [review]
@HAO2167 : Makes sense. I was able to reproduce this and on logging the error really helps. It looks like this:
```
{"level":"error","ts":"2023-08-21T15:07:31-07:00","logger":"InferenceGraphRouter","msg":"An error occurred while preparing request object with serviceUrl.","serviceUrl":"http://single-3.default.{$your-domain}/switch","error":"parse \"http://single-3.default.{$your-domain}/switch\": invalid character \"{\" in host name","stacktrace":"...."}
```

Can you please add a unit test case as well for this ?

**Comment by HAO2167** [comment]
> @HAO2167 : Makes sense. I was able to reproduce this and on logging the error really helps. It looks like this:
> 
> ```
> {"level":"error","ts":"2023-08-21T15:07:31-07:00","logger":"InferenceGraphRouter","msg":"An error occurred while preparing request object with serviceUrl.","serviceUrl":"http://single-3.default.{$your-domain}/switch","error":"parse \"http://single-3.default.{$your-domain}/switch\": invalid character \"{\" in host name","stacktrace":"...."}
> ```
> 
> Can you please add a unit test case as well for this ?

ok， I will add a unit test case.

**Comment by HAO2167** [comment]
@rachitchauhan43 I have already added a  unit test case.

**Comment by rachitchauhan43** [comment]
@HAO2167 : can you fix DCO check ?

File: cmd/router/main_test.go [hunk 2]
```diff
@@ -515,3 +515,53 @@ func TestCallServiceWhenMultipleHeadersToPropagate(t *testing.T) {
 	fmt.Printf("final response:%v\n", response)
 	assert.Equal(t, expectedResponse, response)
 }
+
+func TestModelSwitchExample(t *testing.T) {
+	// Start port-forwarding to istio-ingressgateway
+	portForwardCmd := exec.Command("kubectl", "port-forward", "svc/istio-ingressgateway", "-n", "istio-system", "8080:80")
```
Comment (rachitchauhan43) [inline cmd/router/main_test.go]: I guess this assumes that istio-ingressgateway is there. It is not a unit test rather an integration test. For unit test, you should be able to mock external dependencies.

You just need to test that when callService tries to call a malformed URL then it throws an err that you handled now.

See this unit test [TestCallServiceWhen1HeaderToPropagate](https://github.com/kserve/kserve/blob/68430f9ad8c8848c62520fe9b3028c0158b9227f/cmd/router/main_test.go#L426) for reference.

Comment (HAO2167) [reply cmd/router/main_test.go]: @rachitchauhan43 I added the unit tests and removed integration tests,  I also fixed the DCO check.

File: cmd/router/main_test.go [hunk 3]
```diff
@@ -515,3 +515,16 @@ func TestCallServiceWhenMultipleHeadersToPropagate(t *testing.T) {
 	fmt.Printf("final response:%v\n", response)
 	assert.Equal(t, expectedResponse, response)
 }
+
+
+func TestMalformedURL(t *testing.T) {
+	
+        malformedURL := "http://single-1.default.{$your-domain}/switch"
+        _, _, err := callService(malformedURL, []byte{}, http.Header{})
+        if err == nil {
```
Comment (rachitchauhan43) [inline cmd/router/main_test.go]: @HAO2167 : Can you please do assertion here for the err ?

**Review by rachitchauhan43 — CHANGES_REQUESTED** [review]

File: cmd/router/main_test.go (hunk 3 above)
Comment (HAO2167) [reply cmd/router/main_test.go]: @rachitchauhan43 Okay, I've added it.

**Review by rachitchauhan43 — APPROVED** [review]
LGTM

**Comment by HAO2167** [comment]
@njhill please help me check this pull request , thanks!

File: cmd/router/main_test.go (hunk 3 above)
Comment (yuzisun) [reply cmd/router/main_test.go]: According to the above logic the err should not be nil right?

Comment (yuzisun) [reply cmd/router/main_test.go]: I do not think the testing code is executed

Comment (HAO2167) [reply cmd/router/main_test.go]: @yuzisun My initial thought was to let the test fail using t.fatal because the call service didn't handle the error correctly which caused err == nil. But I think your logic is more correct, so I made the corrections.

**Comment by HAO2167** [comment]
@yuzisun I've rebased the master and pushed it again. Please help me retest. That would be great if this PR got merged soon. I can't wait for my first contribution.

**Comment by yuzisun** [comment]
> @yuzisun I've rebased the master and pushed it again. Please help me retest. That would be great if this PR got merged soon. I can't wait for my first contribution.



> @yuzisun I've rebased the master and pushed it again. Please help me retest. That would be great if this PR got merged soon. I can't wait for my first contribution.

Merged! Thanks for the fix
