### PR TITLE
Handle scenario where annotations are not given in raw deployment mode

### LINKED ISSUE #2560: Cannot run InferenceService in RawDeployment mode without specifying some annotations
/kind bug

**What steps did you take and what happened:**
Configure kserve 0.9 in RawDeployment mode. Run an InferenceService with `metadata: {annotations: null}`.

The mutating web hook fails admission because https://github.com/kserve/kserve/blob/8fdd82fe109967efe94b7a012f07f9d75ab2eb60/pkg/apis/serving/v1beta1/inference_service_defaults.go#L86 doesn't check for nil annotations map before trying to setup a new annotation.

**What did you expect to happen:**

Kserve to be able to deal with an InferenceService in RawDeployment mode without annotations.

**What's the InferenceService yaml:**
From 
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  generateName: inference-service-v2-
  labels:
    inference-service-test.cambridgeconsultants.com: "true"
  annotations:
    hello: ok
spec:
  predictor:
    triton:
      storageUri: "gs://kfserving-examples/models/torchscript"
      runtimeVersion: 20.10-py3
      env:
      - name: OMP_NUM_THREADS
        value: "1"
```

The workaround is to simply add a dummy annotation. Unfortunately `annotations: {}` didn't work. 🤷

**Environment:**

- KServe Version: 0.9
- Cloud Environment: EKS
- Kubernetes version: (use `kubectl version`): v1.21.14
- OS (e.g. from `/etc/os-release`): MacOs

### PR DESCRIPTION
**Pull request by andyi2it**
Signed-off-by: Andrews Arokiam <andrews.arokiam@ideas2it.com>

**What this PR does / why we need it**:
Adds a nil check for annotation and creates one if it is not provided.
Adds a test case for the above change and improves the overall coverage

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2560

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**Feature/Issue validation/testing**:

- Logs

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/apis/serving/v1beta1/inference_service_defaults.go [hunk 1]
```diff
@@ -80,6 +80,9 @@ func (isvc *InferenceService) Default() {
 }
 
 func (isvc *InferenceService) DefaultInferenceService(config *InferenceServicesConfig, deployConfig *DeployConfig) {
+	if isvc.ObjectMeta.Annotations == nil {
+		isvc.ObjectMeta.Annotations = map[string]string{}
```
Comment (yuzisun) [inline pkg/apis/serving/v1beta1/inference_service_defaults.go]: only initialize the annotation map when we add some annotations, can move this into the if block. This way we can still keep the nil semantics that there is no annotations.

File: pkg/apis/serving/v1beta1/inference_service_defaults_test.go [hunk 2]
```diff
@@ -31,63 +31,290 @@ import (
 
 func TestInferenceServiceDefaults(t *testing.T) {
 	g := gomega.NewGomegaWithT(t)
-	config := &InferenceServicesConfig{
-		Explainers: ExplainersConfig{
-			AlibiExplainer: ExplainerConfig{
-				ContainerImage:      "alibi",
-				DefaultImageVersion: "v0.4.0",
+	scenarios := map[string]struct {
```
Comment (yuzisun) [inline pkg/apis/serving/v1beta1/inference_service_defaults_test.go:34]: Thanks for adding the tests!
