### PR TITLE
Fix  InferenceService state when Predictor pod in CrashLoopBackOff 

### LINKED ISSUE #1859: kfserving inference service state shows Ready=True when pods are in CrashLoopBackoff state
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Inference service resource was created as the deployment was created successfully with 1 pod as shown below:
k get pods -A | grep d5ce6b94087b41
`xxx-namespace-xxx     d5ce6b94087b41-predictor-default-vcwhr-deployment-xxxx   3/3     Running              0          11h`

k get deploy -A | grep d5ce6b94087b41
`xxx-namespace-xxx    d5ce6b94087b41-predictor-default-vcwhr-deployment     1/1     1            1           20d`

k get isvc -A | grep d5ce6b94087b41
`xxx-namespace-xxx          d5ce6b94087b41     http://d5ce6b94087b41-xxx-namespace-xxx-xxx.com       True           100                              d5ce6b94087b41-predictor-default-vcwhr    20d`

Due to some scenario, the deployment got restarted. But this time, as there was some problem with the model download storage-initialisation phase, pod got stuck with CrashLoopBackoff state.

Below is the current state of the resources:
k get pods -A | grep d5ce6b94087b41
`xxx-namespace-xxx        d5ce6b94087b41-predictor-default-vcwhr-deployment-oooo    0/3    Init:CrashLoopBackOff   356        40m46s`

k get deploy -A | grep d5ce6b94087b41
`xxx-namespace-xxx          d5ce6b94087b41-predictor-default-vcwhr-deployment     0/1     1            0           20d`

k get isvc -A | grep d5ce6b94087b41
`xxx-namespace-xxx          d5ce6b94087b41     http://d5ce6b94087b41-xxx-namespace-xxx-xxx.com       True           100                              d5ce6b94087b41-predictor-default-vcwhr    20d`

storage-initialiser error:
`Traceback (most recent call last):
  File "./scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/lib/python3.6/site-packages/kfserving/storage.py", line 62, in download
    Storage._download_s3(uri, out_dir)
  File "/usr/lib/python3.6/site-packages/kfserving/storage.py", line 101, in _download_s3
    The path or model %s does not exist." % (uri))
RuntimeError: Failed to fetch model. The path or model s3://bucket-name/test_data/gender does not exist.`

**What did you expect to happen:**
The inference service should reflect the similar status i.e, it should be Ready=False as there are no pods in Running state to serve the requests.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Could reproduce the scenario.
Step1: Create a deployment with a model available in the object store s3. Deployment/Pod/InferenceService are in Running and Ready=True state.
Step2: Delete the model from the object store that is referenced by the deployment.
Step3: Kill the pod and the new pod gets stuck with CrashLoopBackoff state. InferenceService is still in Ready=True state.

No logs were observed in kfserving-controller during the deployment restart and the new pod was trying to come up. Is this an expected behaviour as the Ready=True state is misleading though the deployment/pods are not in Running state?

**Environment:**

- Istio Version: v1.9.7
- Knative Version: v0.18.0
- KFServing Version: v0.5.1
- KFserving-storage-initializer: v0.5.1

- Kubernetes version: (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}`

### PR DESCRIPTION
**Pull request by hdefazio**
**What this PR does / why we need it**:
When deploying a model with an error (e.g. a nonexistent model path) the ISVC modelStatus was stuck in Pending / InProgress. This happened because the Predictor's reconcile function was catching the failing pod's storage initializer container in the running state and never rechecked in order to catch the container in the terminated state. This PR will requeue the Predictor's reconcile function if the storage initializer container is caught in the running state and there was a previous error ( a hint that something may be wrong even if our current status is running). 
The ideal scenario is that we now catch the storage initializer in the terminated state and update the modelStatus to FailedToLoad  / BlockedByFailedLoad. However, the PR also adds a secondary check for serverless deployment so that if we miss the terminated state and the deployment has scaled down to 0, we can retrieve the error status from knative. 

**Type of changes**
Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

Fixes #1859

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Added a unit test to cover the case where we need to use the knative error information to update the ISVC modelStatus
- [ ] Live test:
1. Deployed a model via ODH UI and waited for it to scale to 1
2. Edited the model config to point to a nonexistent model path 
model_config
3. After the deployment has scaled to 0, double checked that the final ISVC modelStatus was FailedToLoad  / BlockedByFailedLoad.
ISVC_final_modelStatus

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

File: pkg/controller/v1beta1/inferenceservice/components/predictor.go [hunk 1]
```diff
@@ -332,6 +333,8 @@ func (p *Predictor) Reconcile(isvc *v1beta1.InferenceService) (ctrl.Result, erro
 	var podLabelValue string
 
 	// Here we allow switch between knative and vanilla deployment
+	kstatus := knservingv1.ServiceStatus{}
```
Comment (spolti) [inline pkg/controller/v1beta1/inferenceservice/components/predictor.go]: why duplicate the envs here?

File: pkg/controller/v1beta1/inferenceservice/components/predictor.go [hunk 2]
```diff
@@ -371,7 +374,10 @@ func (p *Predictor) Reconcile(isvc *v1beta1.InferenceService) (ctrl.Result, erro
 		if err := controllerutil.SetControllerReference(isvc, r.Service, p.scheme); err != nil {
 			return ctrl.Result{}, errors.Wrapf(err, "fails to set owner reference for predictor")
 		}
-		status, err := r.Reconcile()
+
+		var err error
+		status, err = r.Reconcile()
+		fmt.Println("updating status to ", *status)
```
Comment (spolti) [inline pkg/controller/v1beta1/inferenceservice/components/predictor.go]: left over?

File: pkg/apis/serving/v1beta1/inference_service_status.go [hunk 3]
```diff
@@ -565,50 +566,73 @@ func (ss *InferenceServiceStatus) SetModelFailureInfo(info *FailureInfo) bool {
 	return true
 }
 
-func (ss *InferenceServiceStatus) PropagateModelStatus(statusSpec ComponentStatusSpec, podList *v1.PodList, rawDeployment bool) {
+func (ss *InferenceServiceStatus) PropagateModelStatus(statusSpec ComponentStatusSpec, podList *v1.PodList, rawDeployment bool, serviceStatus *knservingv1.ServiceStatus) bool {
```
Comment (spolti) [inline pkg/apis/serving/v1beta1/inference_service_status.go:568]: looking here: https://github.com/kserve/kserve/blob/master/Makefile#L336C1-L337C125

there is no difference between returning true or false, the reconciliation will happen anyway, can you please elaborate on why returning a bool is required?

File: pkg/apis/serving/v1beta1/inference_service_status.go [hunk 4]
```diff
@@ -565,50 +566,73 @@ func (ss *InferenceServiceStatus) SetModelFailureInfo(info *FailureInfo) bool {
...
 	// If the storage initializer is terminated due to error or crashloopbackoff, update model
 	// state to 'ModelLoadFailed' with failure info.
 	for _, cs := range podList.Items[0].Status.InitContainerStatuses {
 		if cs.Name == constants.StorageInitializerContainerName {
 			switch {
 			case cs.State.Running != nil:
-				ss.UpdateModelRevisionStates(Loading, totalCopies, nil)
-				return
+				// Double check that we aren't missing an error
+				if cs.LastTerminationState.Terminated != nil {
```
Comment (spolti) [inline pkg/apis/serving/v1beta1/inference_service_status.go:597]: I am not sure if this extra check here has any effect.

Comment (hdefazio) [reply pkg/apis/serving/v1beta1/inference_service_status.go:597]: The intention was to only re-trigger the reconcile loop if there might be an issue (catch the case where the storage-initializer is looping between an error and running. I was seeing crashloop -> running -> terminated). But if there's no error then it would be a waste to re-check the statuses

File: pkg/apis/serving/v1beta1/inference_service_status.go (hunk 3 above)
Comment (hdefazio) [reply pkg/apis/serving/v1beta1/inference_service_status.go:568]: I'm open to a better solution, I returned bool just for this code block https://github.com/kserve/kserve/blob/cd84424ffd3d14b207c92575f9f026c5693867f3/pkg/controller/v1beta1/inferenceservice/components/predictor.go#L395 - so I would only re-trigger the reconcile loop again if there might be an issue with the storage-initilaizer running status

File: pkg/apis/serving/v1beta1/inference_service_status.go (hunk 4 above)
Comment (spolti) [reply pkg/apis/serving/v1beta1/inference_service_status.go:597]: Ok, please add this explanation as comment.

Comment (spolti) [reply pkg/apis/serving/v1beta1/inference_service_status.go:597]: instead of triggering a new loop, what happens if you set the revision state?

Comment (hdefazio) [reply pkg/apis/serving/v1beta1/inference_service_status.go:597]: Without this change, the last time the reconcile loop happens it catches the storage-initializer in the running state and sets the revision state to Loading. 

I didn't directly just set the revision state to a Failure instead because I really wanted to catch the terminated state (that felt like the most correct sequence of events). The knative failure check is just a backup to make sure that if we still end up missing the terminated state that we don't see the same status issue that this PR is addressing (if we missed the terminated state and didn't check for knative failures we would end up as Pending because the deployment scaled down to 0).

Comment (spolti) [reply pkg/apis/serving/v1beta1/inference_service_status.go:597]: ok, make sense.

**Comment by spolti** [comment]
cc @sivanantha321

File: pkg/apis/serving/v1beta1/inference_service_status.go [hunk 5]
```diff
@@ -565,50 +565,75 @@ func (ss *InferenceServiceStatus) SetModelFailureInfo(info *FailureInfo) bool {
...
+		if !rawDeployment {
+			// Make sure we haven't scaled down to 0 because of an error
+			for _, knativeCond := range serviceStatus.Conditions {
+				if knativeCond.Status == "False" {
+					// If any of the knative statuses are False, the model failed
+					// Hopefully the lastFailureInfo already has the info we need, so we don't update it here
+					ss.UpdateModelRevisionStates(FailedToLoad, totalCopies, nil)
+					return true
+				}
+			}
```
Comment (israel-hdez) [inline pkg/apis/serving/v1beta1/inference_service_status.go:581]: I'm not sure if I'm missing it, but I don't manage to see coverage for these lines in the units. Is it possible to add a unit for this case?

File: pkg/apis/serving/v1beta1/inference_service_status.go [hunk 6]
```diff
@@ -565,50 +565,75 @@ func (ss *InferenceServiceStatus) SetModelFailureInfo(info *FailureInfo) bool {
...
 		if cs.Name == constants.StorageInitializerContainerName {
 			switch {
 			case cs.State.Running != nil:
-				ss.UpdateModelRevisionStates(Loading, totalCopies, nil)
-				return
+				// Double check that we aren't missing an error because the cs is looping between an error state and running
+				if cs.LastTerminationState.Terminated != nil {
+					// Requeue the Predictor reconcile loop if there was a previous error reported
+					// to make sure we aren't just temporarily in the cs.State.Running case before moving to the cs.State.Terminated case
+					return false
```
Comment (israel-hdez) [inline pkg/apis/serving/v1beta1/inference_service_status.go:600]: Also, I'm not seeing coverage for this branch in the units.

From code flow, I'd infer the reported status would be `Pending`. I'm a little bit confused about if that would be a good state to report if the storage initializer is running.

**Review by israel-hdez — COMMENTED** [review]
I think the approach is good.

I left two comments

**Comment by israel-hdez** [comment]
@hdefazio May you rewrite your testing instructions keeping aside the ODH UI?
The ODH UI is not applicable to this project.

**Comment by sivanantha321** [comment]
@hdefazio Can you help sign the commits?  The DCO check is failing.

**Comment by hdefazio** [comment]
@sivanantha321  Just fixed it!

File: pkg/apis/serving/v1beta1/inference_service_status.go (hunk 5 above)
Comment (sivanantha321) [reply pkg/apis/serving/v1beta1/inference_service_status.go:581]: Resolved

**Comment by sivanantha321** [comment]
Nice work!
/lgtm
/approve
