### PR TITLE
Fix for KEDA scaledobject target value is set to pointer instead of specified value

### LINKED ISSUE #4414: KEDA scaledobject target value is set to pointer instead of specified value
/kind bug

**What steps did you take and what happened:**
I have created an InferenceService with KEDA autoscaler, and defined the CPU averageUtilization threshold in the spec. However, the resulting ScaledObject resource sets the metric value to a pointer-like number instead of the provided value of 50.

**What did you expect to happen:**
The ScaledObject created from the InferenceService spec should reflect the given CPU averageUtilization value of 50.

**What's the InferenceService yaml:**
```yaml
apiVersion: "[serving.kserve.io/v1beta1](http://serving.kserve.io/v1beta1)"
kind: "InferenceService"
metadata:
  name: "sklearn-v2-iris"
  annotations:
    [serving.kserve.io/deploymentMode](http://serving.kserve.io/deploymentMode): "RawDeployment"
    [serving.kserve.io/autoscalerClass](http://serving.kserve.io/autoscalerClass): "keda"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v2
      runtime: kserve-sklearnserver
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
    minReplicas: 1
    maxReplicas: 5
    autoScaling:
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: "Utilization"
              averageUtilization: 50
```
**Anything else you would like to add:**

Image

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by andyi2it**
**What this PR does / why we need it**:
The ScaledObject created from the InferenceService spec should reflect the given CPU averageUtilization instead of using the pointer as the target value.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4414 

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**Feature/Issue validation/testing**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?

**Release note**:

```release-note
NONE
```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Comment by yuzisun** [comment]
@andyi2it can you update the PR description ?

File: pkg/controller/v1beta1/inferenceservice/reconcilers/keda/keda_reconciler.go [hunk 1]
```diff
@@ -88,16 +88,14 @@ func getKedaMetrics(componentExt *v1beta1.ComponentExtensionSpec,
 							averageUtil = &constants.DefaultCPUUtilization
 						}
 					}
-					if metric.Resource.Target.AverageUtilization != nil {
-						targetValue = fmt.Sprintf("%d", averageUtil)
-					}
+					targetValue = strconv.Itoa(int(*averageUtil))
```
Comment (andyi2it) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/keda/keda_reconciler.go]: image
Value is being set to the pointer value rather than the provided value of 50

Comment (yuzisun) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/keda/keda_reconciler.go]: Can you help add a test to cover this?  also the average util needs to be integer ?

Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/keda/keda_reconciler.go]: We still need the nil check as there is no default value for memory

**Review by yuzisun — APPROVED** [review]
