### PR TITLE
fix: oci support for storageUris (plural)

### LINKED ISSUE #5200: storageUris with oci:// does not inject modelcar or model volume mounts, while storageUri with oci:// works
/kind bug

**What steps did you take and what happened:**
InferenceService.spec.predictor.storageUris works with s3:// in KServe v0.16, and model.storageUri works with oci://, but storageUris with oci:// does not work. The modelcar container or the storage-initializer container was not found in the pod. The kserve-container reported an error stating that it couldn't find the model in the /mnt/models directory.

**What did you expect to happen:**
I expect the behavior for a single-entry storageURIs to be identical to that of the regular storageURI syntax.

**What's the InferenceService yaml:**
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{},"name":"sklearn-oci-multi","namespace":"default"},"spec":{"predictor":{"model":{"modelFormat":{"name":"sklearn"}},"storageUris":[{"mountPath":"/mnt/models","uri":"oci://rhuss/kserving-example-sklearn:1.0"}]}}}
    modelFormat: sklearn
    serving.kserve.io/deploymentMode: Standard
  creationTimestamp: "2026-03-09T09:31:30Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 1
  name: sklearn-oci-multi
  namespace: default
  resourceVersion: "690320"
  uid: eef5b9f5-4682-43d2-b1f2-d8b022ac166f
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      name: ""
      resources: {}
    storageUris:
    - mountPath: /mnt/models
      uri: oci://rhuss/kserving-example-sklearn:1.0
status:
  clusterServingRuntimeName: kserve-sklearnserver
  components:
    predictor: {}
  conditions:
  - lastTransitionTime: "2026-03-09T09:31:30Z"
    reason: Predictor ingress not created
    status: "False"
    type: IngressReady
  - lastTransitionTime: "2026-03-09T09:31:31Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: PredictorReady
  - lastTransitionTime: "2026-03-09T09:41:31Z"
    reason: Predictor ingress not created
    status: "False"
    type: Ready
  - lastTransitionTime: "2026-03-09T09:31:30Z"
    severity: Info
    status: "False"
    type: Stopped
  deploymentMode: Standard
  modelStatus:
    copies:
      failedCopies: 0
    lastFailureInfo:
      exitCode: 1
      reason: ModelLoadFailed
    states:
      activeModelState: ""
      targetModelState: FailedToLoad
    transitionStatus: BlockedByFailedLoad
  observedGeneration: 1
```

**Anything else you would like to add:**
kserve-container logs:
```
2026-03-09 10:14:23.957 1 kserve ERROR [__main__.py:<module>():39] failed to locate model file for model sklearn-oci-multi under dir /mnt/models,trying loading from model repository.
Traceback (most recent call last):
  File "/sklearnserver/sklearnserver/__main__.py", line 35, in <module>
    model.load()
  File "/sklearnserver/sklearnserver/model.py", line 46, in load
    raise ModelMissingError(model_path)
kserve.errors.ModelMissingError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/sklearnserver/sklearnserver/__main__.py", line 48, in <module>
    registered_models=SKLearnModelRepository(args.model_dir)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sklearnserver/sklearnserver/sklearn_model_repository.py", line 24, in __init__
    self.load_models()
  File "/prod_venv/lib/python3.11/site-packages/kserve/model_repository.py", line 37, in load_models
    for name in os.listdir(self.models_dir):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/models'
```

I am not familiar with KServe's code-base or Go, However, I found that [here](https://github.com/kserve/kserve/blob/0d53816e7cfaedc20fad856bc2de5cd7cad05eb4/pkg/webhook/admission/pod/storage_initializer_injector.go#L223 "storage_initializer_injector"), for URIs with the oci prefix, the function will directly return. 
I also examined the function that [injects modelcar](https://github.com/kserve/kserve/blob/0d53816e7cfaedc20fad856bc2de5cd7cad05eb4/pkg/webhook/admission/pod/storage_initializer_injector.go#L159 "modelcar"). It retrieves the path of oci from the annotation `storage-initializer-sourceuri`. In the pod that uses the storageUri with oci://, I saw the relevant parameters; however, in the pod that uses the storageUris with oci://, I did not see the relevant parameters. I am not sure if this is the cause of the problem.
Part of yaml for pod that uses the storageUri with oci:// : 
```
metadata:
  annotations:
    cni.projectcalico.org/containerID: e11f68a50f25f6a455921adb681028c7d660e9932caaef4caf908064ea0da04b
    cni.projectcalico.org/podIP: 10.42.186.67/32
    cni.projectcalico.org/podIPs: 10.42.186.67/32
    internal.serving.kserve.io/storage-initializer-sourceuri: oci://rhuss/kserving-example-sklearn:1.0
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8080"
    serving.kserve.io/deploymentMode: Standard
    serving.kserve.io/enable-metric-aggregation: "false"
    serving.kserve.io/enable-prometheus-scraping: "false"
```
Part of yaml for pod that uses the storageUris with oci:// : 
```
annotations:
      cni.projectcalico.org/containerID: 727cd0e970c18c8a4af08ba66ccb1779410e270780c726fb74ab390ebaea3e5a
      cni.projectcalico.org/podIP: 10.42.186.90/32
      cni.projectcalico.org/podIPs: 10.42.186.90/32
      prometheus.kserve.io/path: /metrics
      prometheus.kserve.io/port: "8080"
      serving.kserve.io/deploymentMode: Standard
      serving.kserve.io/enable-metric-aggregation: "false"
      serving.kserve.io/enable-prometheus-scraping: "false"
```

Thank you for making and maintaining KServe!

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version: v0.16.0 (Standard)
- Cloud Environment: 
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): v1.29.11
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by brucearctor**
## What this PR does

Fixes #5200

### Problem
`storageUris` (plural) with `oci://` URIs did not inject the modelcar sidecar or model volume mounts, causing the model container to fail with `FileNotFoundError: /mnt/models`. The same `oci://` URI worked correctly with the singular `storageUri`.

### Root Cause
`CommonStorageInitialization()` early-returned `nil` when OCI URIs were detected, correctly skipping init-container injection (OCI uses a sidecar, not init-containers), but failing to perform the modelcar injection. The singular `storageUri` path worked because it relied on annotations + the `InjectModelcar()` webhook, which the `storageUris` path bypasses.

### Fix
Instead of early-returning, `CommonStorageInitialization()` now calls `ConfigureModelcarToContainer()` for each OCI URI when using the `storageUris` path (`IsLegacyURI == false`). This injects:
- Modelcar sidecar container
- Modelcar init container (for pre-fetching)
- Shared volume + mounts
- `ShareProcessNamespace = true`
- `MODEL_INIT_MODE=async` env var

The legacy path (`IsLegacyURI == true`) behavior is preserved — it continues to rely on annotations + the `InjectModelcar()` webhook.

### Testing
Added `TestCommonStorageInitializationWithOciURI` with 4 sub-tests:
- OCI URI via storageUris injects modelcar (core fix)
- OCI URI with transformer injects modelcar for both containers
- Legacy OCI URI path still returns nil (backward compatibility)
- OCI URI with worker container only (multi-node fallback)

All existing tests pass with no regressions.

### CODE REVIEW

**Review by vivekk16 — COMMENTED** [review]
We require all commits to be signed. Please refer to the github doc on how to sign commits: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

And please ensure the PR title follows the expected format:
https://github.com/kserve/kserve/blob/master/.github/workflows/pr-style-check.yml

**Comment by brucearctor** [comment]
Makes sense.  Will do.  I thought I had signed commits configured.  But,
seems not.

**Comment by brucearctor** [comment]
@vivekk16 -- got the title/lint fixed.  And signing key.  Cheers-

File: pkg/webhook/admission/pod/storage_initializer_injector.go [hunk 1]
```diff
@@ -235,9 +235,48 @@ func CommonStorageInitialization(ctx context.Context, params *StorageInitializer
...
+				return errors.New("Invalid configuration: cannot find container")
+			}
+
+			for _, storageUri := range params.StorageURIs {
+				if !strings.HasPrefix(storageUri.Uri, constants.OciURIPrefix) {
+					continue
+				}
+				targetContainerName := constants.InferenceServiceContainerName
+				if userContainer == nil {
+					targetContainerName = constants.WorkerContainerName
```
Comment (spolti) [inline pkg/webhook/admission/pod/storage_initializer_injector.go:266]: @Jooho please take a look. I guess we need to double check it for multi-node and llmisvc.

**Review by israel-hdez — COMMENTED** [review]
These changes only work if there is a single OCI source in the list of storageUris. @brucearctor would you be willing to add support for more than one?

**Comment by brucearctor** [comment]
> These changes only work if there is a single OCI source in the list of storageUris. @brucearctor would you be willing to add support for more than one?

FWIW:  I did recognize htat in the submission.  BUT, figured some progress, which addressed the issue was better than holding out and writing more and more code.

@israel-hdez Is that a blocker?  And, need that addressed in this PR?  Or, get the tests passing, and then follow this PR with another allowing more than one?  [ has been like 5/6 weeks since I submitted this -- so will have to refresh on the content/context here ]

**Comment by israel-hdez** [comment]
Hey @brucearctor . If this is intended, I don't think this is a blocker for merging.

That said, in my org, we require the support for more than one quite soon. Are you planning to follow-up quickly? If not, we will.

**Comment by brucearctor** [comment]
> /rerun-all

I am not sure how to easily fix the failed tests, if can't see logs!?  Is that a settings/config issue?

I can try to work around.

https://github.com/kserve/kserve/actions/runs/23354495950/job/68799576581?pr=5261

https://github.com/kserve/kserve/actions/runs/23354495933/job/68799576629?pr=5261

Screenshot 2026-04-28 at 10 52 05 AM
Screenshot 2026-04-28 at 10 52 10 AM

**Comment by israel-hdez** [comment]
@brucearctor If you can do a rebase and push again the rebased commit, that will trigger another CI run. Logs have expired, and I don't have powers to re-run.

**Comment by Jooho** [comment]
closed and reopened to trigger ci.

**Review by Jooho — APPROVED** [review]

**Comment by brucearctor** [comment]
> Hey @brucearctor . If this is intended, I don't think this is a blocker for merging.
> 
> That said, in my org, we require the support for more than one quite soon. Are you planning to follow-up quickly? If not, we will.

@israel-hdez  -- working on the follow up.  Not even because I need, but as a way to contribute to the community.  Cheers -

https://github.com/kserve/kserve/pull/5470

Still in the works.  But, imagine wrapping tonight.
