### PR TITLE
disallow `name` field in standard predictor

### LINKED ISSUE #4472: Adding name field to non-custom predictor incorrectly triggers custom container logic
/kind bug

**What steps did you take and what happened:**
After adding a `name` field inside standard predictor blocks (e.g., sklearn, tensorflow), the system allowed me to create the `inferenceservice`, but failed at deployment time with an error indicating that the container `kserve-container` cannot be found.

**What did you expect to happen:**
If the predictor is non-custom ones, it's container should only be assigned to the default container, "kserve-container", based on the internal logic,  and should not be user-configurable. If a user explicitly sets a `name` field under a standard predictor block, there should be an error message stopping the user at creation time, instead of letting he/she proceeds to a failure during revision deployment.

**What's the InferenceService yaml:**

To be more specific, here is a minimal example:

```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris-example"
spec:
  predictor:
    minReplicas: 1
    sklearn:
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
      protocolVersion: v1
      name: "sklearn-iris-predictor"
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
```

This leads to the following failure (shown by `kubectl get isvc $name -n $namespace -o yaml`): 

```bash
 message: 'Revision "sklearn-iris-example-predictor-00001" failed with message:
  admission webhook "inferenceservice.kserve-webhook-server.pod-mutator" denied
  the request: Invalid configuration: cannot find container: kserve-container.'
reason: RevisionFailed
severity: Info
status: "False"
type: PredictorConfigurationReady
```
When the `name:` field under `sklearn` is removed, the deployment works as expected.

**Root cause analysis:**

Tracing through the code suggests that specifying the `name:`  under a standard predictor (which is supposed to be non-customized)results in container name handling being unintentionally overridden. This likely causes both standard and custom predictor logic paths to be triggered simultaneously.

Normally, a standard predictor won't and shouldn't specified a `name:` field. The default function will automatically assign it like this: 
`k.Container.Name = constants.InferenceServiceContainerName`

And if it is a custom predictor, which you don't need to specified a predictor pod name (‵PodSpec `json:",inline"`), the default function will do this:
```go
// Default sets defaults on the resource
func (c *CustomPredictor) Default(config *InferenceServicesConfig) {
	if len(c.Containers) == 0 {
		c.Containers = append(c.Containers, corev1.Container{})
	}
	if len(c.Containers) == 1 || len(c.Containers[0].Name) == 0 {
		c.Containers[0].Name = constants.InferenceServiceContainerName
	}
	setResourceRequirementDefaults(config, &c.Containers[0].Resources)
}
```
[an example of custom predictor is here](https://kserve.github.io/website/0.8/modelserving/v1beta1/custom/custom_model/#deploy-the-custom-predictor-on-kserve)
It allows users to input their own container name, or will be `kserve-container` as default.

But when it comes to specifying `name:` field in a standard predictor, it seems like it not only activate the standard defaulting logic of standard predictor, but also accidentally activate part of the custom predictor path. And so leads to the overwrite in container name, which create error when `kserve-container` can't be found.

Also, because custom predictors do not require a predictor type keyword (like `sklearn:` or `triton:`), the mutual exclusive check is not triggered either, which allows both paths to co-exist unexpectedly.

( Maybe ensuring mutual exclusivity logic correctly differentiates between customized and standard predictor paths can be a good start to solve this issue ?) 

**Environment:**

- Istio Version: 1.23.2
- Knative Version: v1.15.2
- KServe Version: v0.15.0
- Kubeflow version: No
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version: kind v0.28.0
- Kubernetes version: (use `kubectl version`): v1.32.3
- OS (e.g. from `/etc/os-release`): Ubuntu 24.04

**Additional Context**

I'm trying to fix this issue and would really appreciate any design or implementation suggestions !

### PR DESCRIPTION
**Pull request by HutakiHare**
**What this PR does / why we need it**:
This PR adds validation to catch misconfiguration in the `name` field of standard predictor in creation time.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4472

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:
+ Add unit test: TestInvalidNameInSklearnPredictor
+ Verify webhook behavior by applying InferenceService with a non-empty `name` field in a simulated env
+ Ran make test, the newly added test passed (one test, v1alpha1/inferencegraph/suite_test.go, didn't pass, but it is not related to my modification)

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [x] Unit test: Added `TestInvalidNameInSklearnPredictor` in `inference_service_validation_test.go` to test the newly added `validatePredictor` function in `inference_service_validation.go`. This test verifies that an error is returned when the `name` field is set in a standard predictor (e.g. Sklearn), which is not allowed.
- [x] Behavior test: Create a temporary docker image and loaded to `kind` to simulate the undated environment. Applied standard predictors with `name` field to verify that the webhook correctly trigger `validatePredictor` during InferenceService creation and block invalid configurations at creation time.

- Logs

**Special notes for your reviewer**:
- I ran both `make test` and `make precommit` at the root level:
  - `make test` failed due to **one unrelated unit test**, which is **not affected by my changes**.
  - `make precommit` failed with the following error:
    > the go language version (go1.23) used to build golangci-lint is lower than the target Go version (1.24)

    Even after upgrading to Go 1.24 and rebuilding `golangci-lint`, the issue persisted.

- My changes are **limited to**:
  - `inference_service_validation.go`
  - `inference_service_validation_test.go`

- To ensure correctness:
  - I ran `make test -v` inside the `pkg/controller/inferenceservice/resources/knative/serving/v1beta1` (or appropriate) directory, and **my unit tests passed**.
  - I also ran the **behavioral test** to confirm the new validation logic works as intended.

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
Validation added to prevent setting the `name` field in standard predictor.
```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

File: pkg/apis/serving/v1beta1/inference_service_validation.go [hunk 1]
```diff
@@ -49,6 +49,8 @@ var (
 	validatorLogger = logf.Log.WithName("inferenceservice-v1beta1-validation-webhook")
 	// IsvcRegexp regular expressions for validation of isvc name
 	IsvcRegexp = regexp.MustCompile("^" + IsvcNameFmt + "$")
+
+	log = logf.Log.WithName("InferenceServiceValidation")
```
Comment (sivanantha321) [inline pkg/apis/serving/v1beta1/inference_service_validation.go]: There is already a logger configured in the line 49.

Comment (HutakiHare) [reply pkg/apis/serving/v1beta1/inference_service_validation.go]: You are right. Let me get rid of it now. Thanks!

**Comment by sivanantha321** [comment]
@HutakiHare Can you help fix the lint error ?

**Comment by HutakiHare** [comment]
> @HutakiHare Can you help fix the lint error ?

Sure! I would like give it a try.

**Comment by sivanantha321** [comment]
> > @HutakiHare Can you help fix the lint error ?
> 
> Sure! I would like give it a try.

btw, you just have to run `make precommit`

**Comment by HutakiHare** [comment]
> > > @HutakiHare Can you help fix the lint error ?
> > 
> > 
> > Sure! I would like give it a try.
> 
> btw, you just have to run `make precommit`

ok ! Thanks a lot

**Comment by HutakiHare** [comment]
@sivanantha321 Could you help rerun the checker?
I synced with master, and the precommit checks are now passing locally. Thank you!

**Comment by sivanantha321** [comment]
> @sivanantha321 Could you help rerun the checker? I synced with master, and the precommit checks are now passing locally. Thank you!

Done

**Comment by sivanantha321** [comment]
Thanks for the improvement!
/lgtm
/approve

**Review by sivanantha321 — APPROVED** [review]
