### PR TITLE
fix: surface failure conditions in InferenceService status

### LINKED ISSUE #5113: The status is not available for the InferenceService
/kind bug

**What steps did you take and what happened:**

After we create an InferenceService, there should be the section status created for this InferenceService, showing the status for this service. However, when we create the inference service with the following content, the section of status is empty in the CR of the InferenceService.

**What did you expect to happen:**
We expect the CR InferenceService has at least the status section, indicating the status of the inference service, which could be even an error or without error.

**What's the InferenceService yaml:**
The content of the YAML is:

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    ds.bloomberg.com/gpuSubtype: bloomberg.com/gpu-h200
    identities.bloomberg.com/bcs: kserve-workshop
    identities.bloomberg.com/initContainerNames: storage-initializer
    serving.kserve.io/deploymentMode: Standard
  name: demo-triton-test-1
  namespace: s-dsplatform
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      name: ""
      resources:
        limits:
          cpu: "4"
          memory: 8Gi
          nvidia.com/mig-1g.18gb: "1"
        requests:
          cpu: "4"
          memory: 8Gi
          nvidia.com/mig-1g.18gb: "1"
      runtime: kserve-tritonserver
      storageUri: s3://kserve-workshop/models/triton
```

As you see there is annotation key `identities.bloomberg.com/bcs`, we specify the value is kserve-workshop. This is name of the CR bcsidentity we need to specify. If the cluster has the bcsidentity kserve-workshop available under the same namespace, the pod named demo-triton-test-1-predictor-76f6bf9cbd-jnvzf is created, but with the following error:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bms-discovery.host: "true"
    cni.projectcalico.org/containerID: f3c427e7629e1e67e3fe96161030b549249b5fa036ac820cc02ffd48267b214c
    cni.projectcalico.org/podIP: 10.244.181.30/32
    cni.projectcalico.org/podIPs: 10.244.181.30/32
    ds.bloomberg.com/gpuSubtype: bloomberg.com/gpu-h200
    identities.bloomberg.com/bcs: kserve-workshop
    identities.bloomberg.com/initContainerNames: storage-initializer
    internal.serving.kserve.io/storage-initializer-sourceuri: s3://kserve-workshop/models/triton
    prometheus.io/scrape: "true"
    serving.kserve.io/deploymentMode: Standard
    serving.kserve.io/enable-metric-aggregation: "false"
    serving.kserve.io/enable-prometheus-scraping: "false"
  creationTimestamp: "2026-02-23T17:13:01Z"
  generateName: demo-triton-test-1-predictor-76f6bf9cbd-
  generation: 1
  labels:
    app: isvc.demo-triton-test-1-predictor
    app.kubernetes.io/instance: demo-triton-test-1
    app.kubernetes.io/kind: InferenceService
    app.kubernetes.io/uid: 9a307b86-577e-4c57-b014-7f97bbbd5093
    component: predictor
    pod-template-hash: 76f6bf9cbd
    service.istio.io/canonical-name: demo-triton-test-1-predictor
    serving.kserve.io/inferenceservice: demo-triton-test-1
  name: demo-triton-test-1-predictor-76f6bf9cbd-jnvzf
  namespace: s-dsplatform
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: demo-triton-test-1-predictor-76f6bf9cbd
    uid: 6af6ea95-eea7-42be-8ffa-7d3e9a42138e
  resourceVersion: "288969240"
  uid: 831f84a2-b9d8-4cfe-9a61-163788e8b778
spec:
  containers:
  - args:
    - tritonserver
    - --model-store=/mnt/models
    - --grpc-port=9000
    - --http-port=8080
    - --allow-grpc=true
    - --allow-http=true
    env:
    - name: DSP_CLUSTER_NAME
      value: inference-kaas-qa-01-pw
    - name: DSP_CLUSTER_TIER
      value: qa
    - name: GUTS_METRICS_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: GUTS_TRACE_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
      value: "true"
    - name: MKL_NUM_THREADS
      value: "4"
    - name: NUMEXPR_NUM_THREADS
      value: "4"
    - name: NUM_THREADS
      value: "4"
    - name: OMP_NUM_THREADS
      value: "4"
    - name: OPENBLAS_NUM_THREADS
      value: "4"
    - name: VECLIB_MAXIMUM_THREADS
      value: "4"
    image: artifactory.inf.bloomberg.com/ds/ext/nvcr.io/nvidia/tritonserver:23.05-py3
    imagePullPolicy: IfNotPresent
    name: kserve-container
    ports:
    - containerPort: 8080
      name: api
      protocol: TCP
    - containerPort: 8002
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 8080
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "4"
        ephemeral-storage: 200Gi
        memory: 8Gi
        nvidia.com/mig-1g.18gb: "1"
        nvidia.com/nvidia-h200-mig-1g.18gb: "1"
      requests:
        cpu: "4"
        ephemeral-storage: 4Mi
        memory: 8Gi
        nvidia.com/mig-1g.18gb: "1"
        nvidia.com/nvidia-h200-mig-1g.18gb: "1"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      runAsNonRoot: true
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p4qgm
      readOnly: true
    - mountPath: /mnt/models
      name: kserve-provision-location
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - s3://kserve-workshop/models/triton
    - /mnt/models
    env:
    - name: DSP_CLUSTER_NAME
      value: inference-kaas-qa-01-pw
    - name: DSP_CLUSTER_TIER
      value: qa
    - name: BCS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: bcs-access-key
          name: bcs-secret-kserve-workshop
    - name: BCS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: bcs-secret-access-key
          name: bcs-secret-kserve-workshop
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: bcs-access-key
          name: bcs-secret-kserve-workshop
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: bcs-secret-access-key
          name: bcs-secret-kserve-workshop
    - name: BCS_HOST
      value: http://s3.dev.bcs.bloomberg.com
    - name: AWS_ENDPOINT_URL
      value: http://s3.dev.bcs.bloomberg.com
    - name: S3_ENDPOINT
      value: s3.dev.bcs.bloomberg.com
    - name: S3_USE_HTTPS
      value: "0"
    - name: AWS_REGION
      value: us-east-2
    - name: HF_HUB_ENABLE_HF_TRANSFER
      value: "1"
    - name: HF_XET_HIGH_PERFORMANCE
      value: "1"
    - name: HF_XET_NUM_CONCURRENT_RANGE_GETS
      value: "8"
    image: artifactory.inf.bloomberg.com/ds/ext/registry-1.docker.io/kserve/storage-initializer:v0.16.0
    imagePullPolicy: IfNotPresent
    name: storage-initializer
    resources:
      limits:
        cpu: "1"
        ephemeral-storage: 200Gi
        memory: 1Gi
      requests:
        cpu: 100m
        ephemeral-storage: 4Mi
        memory: 100Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /mnt/models
      name: kserve-provision-location
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p4qgm
      readOnly: true
  nodeName: pw-0207001
  preemptionPolicy: PreemptLowerPriority
  priority: 5000000
  priorityClassName: ds-dev
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: nvidia.com/mig-1g.18gb
    operator: Exists
  - effect: NoSchedule
    key: nvidia.com/nvidia-h200-mig-1g.18gb
    operator: Exists
  volumes:
  - name: kube-api-access-p4qgm
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  - emptyDir: {}
    name: kserve-provision-location
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-02-23T17:13:03Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-02-23T17:13:01Z"
    message: 'containers with incomplete status: [storage-initializer]'
    reason: ContainersNotInitialized
    status: "False"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-02-23T17:13:01Z"
    message: 'containers with unready status: [kserve-container]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-02-23T17:13:01Z"
    message: 'containers with unready status: [kserve-container]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-02-23T17:13:01Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: artifactory.inf.bloomberg.com/ds/ext/nvcr.io/nvidia/tritonserver:23.05-py3
    imageID: ""
    lastState: {}
    name: kserve-container
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p4qgm
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /mnt/models
      name: kserve-provision-location
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 100.90.128.109
  hostIPs:
  - ip: 100.90.128.109
  initContainerStatuses:
  - allocatedResources:
      cpu: 100m
      ephemeral-storage: 4Mi
      memory: 100Mi
    containerID: containerd://afdc722925827a82223b860a95e1eb1052b5c4e755156724f66ab616ca1d5bcb
    image: artifactory.inf.bloomberg.com/ds/ext/registry-1.docker.io/kserve/storage-initializer:v0.16.0
    imageID: artifactory.inf.bloomberg.com/ds/ext/registry-1.docker.io/kserve/storage-initializer@sha256:8027889c9311e28fa9f329e896bb54c6a37d254484d67668454a0ced4a918dec
    lastState:
      terminated:
        containerID: containerd://afdc722925827a82223b860a95e1eb1052b5c4e755156724f66ab616ca1d5bcb
        exitCode: 1
        finishedAt: "2026-02-23T20:38:51Z"
        message: |
          -packages/botocore/hooks.py", line 256, in emit
              return self._emit(event_name, kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/prod_venv/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
              response = handler(**kwargs)
                         ^^^^^^^^^^^^^^^^^
            File "/prod_venv/lib/python3.11/site-packages/botocore/retryhandler.py", line 207, in __call__
              if self._checker(**checker_kwargs):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/prod_venv/lib/python3.11/site-packages/botocore/retryhandler.py", line 284, in __call__
              should_retry = self._should_retry(
                             ^^^^^^^^^^^^^^^^^^^
            File "/prod_venv/lib/python3.11/site-packages/botocore/retryhandler.py", line 320, in _should_retry
              return self._checker(attempt_number, response, caught_exception)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/prod_venv/lib/python3.11/site-packages/botocore/retryhandler.py", line 363, in __call__
              checker_response = checker(
                                 ^^^^^^^^
            File "/prod_venv/lib/python3.11/site-packages/botocore/retryhandler.py", line 247, in __call__
              return self._check_caught_exception(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/prod_venv/lib/python3.11/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
              raise caught_exception
            File "/prod_venv/lib/python3.11/site-packages/botocore/endpoint.py", line 279, in _do_get_response
              http_response = self._send(request)
                              ^^^^^^^^^^^^^^^^^^^
            File "/prod_venv/lib/python3.11/site-packages/botocore/endpoint.py", line 383, in _send
              return self.http_session.send(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/prod_venv/lib/python3.11/site-packages/botocore/httpsession.py", line 493, in send
              raise EndpointConnectionError(endpoint_url=request.url, error=e)
          botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://s3.dev.bcs.bloomberg.com/kserve-workshop?prefix=models%2Ftriton&encoding-type=url"
        reason: Error
        startedAt: "2026-02-23T20:38:45Z"
    name: storage-initializer
    ready: false
    resources:
      limits:
        cpu: "1"
        ephemeral-storage: 200Gi
        memory: 1Gi
      requests:
        cpu: 100m
        ephemeral-storage: 4Mi
        memory: 100Mi
    restartCount: 44
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=storage-initializer pod=demo-triton-test-1-predictor-76f6bf9cbd-jnvzf_s-dsplatform(831f84a2-b9d8-4cfe-9a61-163788e8b778)
        reason: CrashLoopBackOff
    user:
      linux:
        gid: 1000
        supplementalGroups:
        - 1000
        uid: 1000
    volumeMounts:
    - mountPath: /mnt/models
      name: kserve-provision-location
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p4qgm
      readOnly: true
      recursiveReadOnly: Disabled
  phase: Pending
  podIP: 10.244.181.30
  podIPs:
  - ip: 10.244.181.30
  qosClass: Burstable
  startTime: "2026-02-23T17:13:01Z"
```

If the the bcsidentity kserve-workshop is not available in the cluster, the pod is never created, the deployment shows as below:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    bms-discovery.host: "true"
    deployment.kubernetes.io/revision: "1"
    ds.bloomberg.com/gpuSubtype: bloomberg.com/gpu-h200
    identities.bloomberg.com/bcs: kserve-workshop
    identities.bloomberg.com/initContainerNames: storage-initializer
    internal.serving.kserve.io/storage-initializer-sourceuri: s3://kserve-workshop/models/triton
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8002"
    serving.kserve.io/deploymentMode: Standard
  creationTimestamp: "2026-02-23T20:46:27Z"
  generation: 1
  labels:
    app: isvc.demo-triton-test-1-predictor
    component: predictor
    serving.kserve.io/inferenceservice: demo-triton-test-1
  name: demo-triton-test-1-predictor
  namespace: s-dsplatform
  ownerReferences:
  - apiVersion: serving.kserve.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: InferenceService
    name: demo-triton-test-1
    uid: fd3ad44c-cccf-4f17-b8fb-37479723fb5e
  resourceVersion: "175602467"
  uid: 86638aaf-0b3f-4d5a-af0e-55f6bbaa008c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: isvc.demo-triton-test-1-predictor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        bms-discovery.host: "true"
        ds.bloomberg.com/gpuSubtype: bloomberg.com/gpu-h200
        identities.bloomberg.com/bcs: kserve-workshop
        identities.bloomberg.com/initContainerNames: storage-initializer
        internal.serving.kserve.io/storage-initializer-sourceuri: s3://kserve-workshop/models/triton
        prometheus.kserve.io/path: /metrics
        prometheus.kserve.io/port: "8002"
        serving.kserve.io/deploymentMode: Standard
      creationTimestamp: null
      labels:
        app: isvc.demo-triton-test-1-predictor
        component: predictor
        service.istio.io/canonical-name: demo-triton-test-1-predictor
        serving.kserve.io/inferenceservice: demo-triton-test-1
      name: demo-triton-test-1-predictor
      namespace: s-dsplatform
    spec:
      containers:
      - args:
        - tritonserver
        - --model-store=/mnt/models
        - --grpc-port=9000
        - --http-port=8080
        - --allow-grpc=true
        - --allow-http=true
        image: artifactory.inf.bloomberg.com/ds/ext/nvcr.io/nvidia/tritonserver:23.05-py3
        imagePullPolicy: IfNotPresent
        name: kserve-container
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
            nvidia.com/mig-1g.18gb: "1"
          requests:
            cpu: "4"
            memory: 8Gi
            nvidia.com/mig-1g.18gb: "1"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2026-02-23T20:46:27Z"
    lastUpdateTime: "2026-02-23T20:46:27Z"
    message: Created new replica set "demo-triton-test-1-predictor-d9855dc75"
    reason: NewReplicaSetCreated
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-02-23T20:46:27Z"
    lastUpdateTime: "2026-02-23T20:46:27Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2026-02-23T20:46:27Z"
    lastUpdateTime: "2026-02-23T20:46:27Z"
    message: 'admission webhook "pod.bcsidentity.identity.bloomberg.com" denied the
      request: BCSIdentity.identity.bloomberg.com "kserve-workshop" not found'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 1
  unavailableReplicas: 1
```

This is what the InferenceService CR shows us:
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    bms-discovery.host: "true"
    ds.bloomberg.com/gpuSubtype: bloomberg.com/gpu-h200
    identities.bloomberg.com/bcs: kserve-workshop
    identities.bloomberg.com/initContainerNames: storage-initializer
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{"ds.bloomberg.com/gpuSubtype":"bloomberg.com/gpu-h200","identities.bloomberg.com/bcs":"kserve-workshop","identities.bloomberg.com/initContainerNames":"storage-initializer","serving.kserve.io/deploymentMode":"Standard"},"name":"demo-triton-test-1","namespace":"s-dsplatform"},"spec":{"predictor":{"model":{"modelFormat":{"name":"pytorch"},"name":"","resources":{"limits":{"cpu":"4","memory":"8Gi","nvidia.com/mig-1g.18gb":"1"},"requests":{"cpu":"4","memory":"8Gi","nvidia.com/mig-1g.18gb":"1"}},"runtime":"kserve-tritonserver","storageUri":"s3://kserve-workshop/models/triton"}}}}
    serving.kserve.io/deploymentMode: Standard
  creationTimestamp: "2026-02-23T20:46:27Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 1
  labels:
    app: bms-discovery
  name: demo-triton-test-1
  namespace: s-dsplatform
  resourceVersion: "175602452"
  uid: fd3ad44c-cccf-4f17-b8fb-37479723fb5e
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      name: ""
      resources:
        limits:
          cpu: "4"
          memory: 8Gi
          nvidia.com/mig-1g.18gb: "1"
        requests:
          cpu: "4"
          memory: 8Gi
          nvidia.com/mig-1g.18gb: "1"
      runtime: kserve-tritonserver
      storageUri: s3://kserve-workshop/models/triton
```

There is not `status` at all for this inference service.

**Anything else you would like to add:**

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: 0.16, latest.
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by houshengbo**
Fixes: #5113

Two root causes fixed:

Bug 1 - Status section empty on early reconciliation failures:
- Call InitializeConditions() early in Reconcile() before any early-return path.
- Add updateStatus() before every early-return error path in controller.go.
- Call PropagateRawStatusWithMessages() on reconcile failure in predictor.go, transformer.go, and explainer.go for both Standard and Knative modes.
- Guard against empty deploymentList in PropagateRawStatus() to prevent panic.

Bug 2 - Deployment failure conditions silently lost in Standard mode:
- DeploymentReconciler.Reconcile() was returning in-memory desired-state deployments (empty .Status) instead of the server-side existing deployments (with live .Status.Conditions like ReplicaFailure). Introduce resultList to return the correct server-side object per reconcile outcome.

Tests added:
- Unit: TestDeploymentReconciler_Reconcile
- Unit: TestPropagateRawStatus_EmptyDeploymentList
- Unit: TestPropagateRawStatusWithMessages_AllComponents
- Integration: replica failure condition (e.g. admission webhook denial) propagated to InferenceService PredictorReady condition

### CODE REVIEW

**Review by cjohannsen-cloudera — APPROVED** [review]
LGTM

File: pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go [hunk 1]
```diff
@@ -9813,6 +9813,105 @@ var _ = Describe("v1beta1 inference service controller", func() {
...
+// TestDeploymentReplicaFailurePropagatedToIsvcStatus is an integration test that covers
+// the combined fix for Bug 1 and Bug 2 from issue #5113.
+//
+// Bug 1: Without InitializeConditions on early paths the ISVC status could be completely
+// empty. After the fix the status section must always contain at least the "Ready"
+// condition once the first reconciliation cycle completes.
+//
+// Bug 2: Previously, DeploymentReconciler.Reconcile returned the in-memory desired
+// deployment (no .Status.Conditions) instead of the server-side existing deployment.
+// As a result, a ReplicaFailure condition (e.g. from an admission-webhook like BCSIdentity
```
Comment (cmaddalozzo) [inline pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go]:
```suggestion
// As a result, a ReplicaFailure condition (e.g. from an admission-webhook
```

**Review by sivanantha321 — APPROVED** [review]
