### PR TITLE
Enrich isvc NotReady events for failed conditions 

### LINKED ISSUE #2962: Emit kubernetes events for the model status
/kind feature
We'd like to use Prometheus to alert on if the model load has failed, i.e, `ModelLoadFailed`. Currently, we can see the load failure in the yaml:
``` 
  modelStatus:
      copies:
        failedCopies: 0
        totalCopies: 1
      lastFailureInfo:
        exitCode: 137
        reason: ModelLoadFailed
      states:
        activeModelState: Loaded
        targetModelState: Loaded
      transitionStatus: UpToDate
```

However, if Kubernetes events could be created for changes in the model state, especially failures, it would make it much easier to have automated alerting on model status failures. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by asdqwe123zxc**
**What this PR does / why we need it**:
- Add failed conditions for the NotReady event
- Bug fix for generating false event when deployment is in progress

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2962

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

File: pkg/controller/v1beta1/inferenceservice/controller_test.go [hunk 1]
```diff
@@ -2088,3 +2091,15 @@ var _ = Describe("v1beta1 inference service controller", func() {
 		})
 	})
 })
+
+func TestGetEvent(t *testing.T) {
+
+	applyCmd := exec.Command("kubectl", "apply", "-f", "https://raw.githubusercontent.com/kserve/kserve/master/docs/samples/v1beta1/onnx/onnx.yaml")
```
Comment (lizzzcai) [inline pkg/controller/v1beta1/inferenceservice/controller_test.go]: I think this is not the best practice to use a public url here as it might change. Can you find the best  practice to test event, maybe can refer [here](https://github.com/kubernetes/kubernetes/blob/fa66a37fd9bdf4e56bc86695dbdf0c7484ba86eb/staging/src/k8s.io/client-go/tools/record/event_test.go).

Comment (asdqwe123zxc) [reply pkg/controller/v1beta1/inferenceservice/controller_test.go]: Oops...I think I accidently commited while testing some ideas. Actually, we're trying to do it in non-url ways currently. Thanks for the tip!

**Comment by lizzzcai** [comment]
@yuzisun can you help to take a look at this PR.

File: pkg/controller/v1beta1/inferenceservice/controller.go [hunk 2]
```diff
@@ -369,3 +378,19 @@ func (r *InferenceServiceReconciler) deleteExternalResources(isvc *v1beta1api.In
 	}
 	return nil
 }
+
+func (r *InferenceServiceReconciler) GetFailConditions(isvc *v1beta1api.InferenceService) string {
+	/*
+		logf.SetLogger(zap.New())
+		log := logf.Log.WithName("my_controller")
+		log.Info("GetFailConditions")
+		fmt.Println("my_GetFailConditions")
```
Comment (spolti) [inline pkg/controller/v1beta1/inferenceservice/controller.go]: left over?

File: pkg/controller/v1beta1/inferenceservice/controller_test.go [hunk 3]
```diff
@@ -2188,4 +2188,134 @@ var _ = Describe("v1beta1 inference service controller", func() {
 			}, timeout, interval).Should(BeTrue())
 		})
 	})
+	Context("If the InferenceService occured any error", func() {
```
Comment (spolti) [inline pkg/controller/v1beta1/inferenceservice/controller_test.go:2192]: I didn't spot here where you are asserting the events from k8s to make sure the event was published.

File: pkg/controller/v1beta1/inferenceservice/controller.go [hunk 4]
```diff
@@ -369,3 +378,19 @@ func (r *InferenceServiceReconciler) deleteExternalResources(isvc *v1beta1api.In
...
+	*/
+	msg := ""
+	for _, cond := range isvc.Status.Conditions {
+		if string(cond.Status) == "False" {
+			msg = fmt.Sprintf("%s, %s", msg, string(cond.Type))
```
Comment (spolti) [inline pkg/controller/v1beta1/inferenceservice/controller.go]: How will this be shown in the events if there is more than 1 condition?

File: pkg/controller/v1beta1/inferenceservice/controller.go (hunk 2 above)
Comment (asdqwe123zxc) [reply pkg/controller/v1beta1/inferenceservice/controller.go]: Yes, it's a missed deleted part of the draft. We'll take care of this, thanks!

File: pkg/controller/v1beta1/inferenceservice/controller.go (hunk 4 above)
Comment (asdqwe123zxc) [reply pkg/controller/v1beta1/inferenceservice/controller.go]: For example: " InferenceService [test-err-msg] is not Ready because of: IngressReady, PredictorReady "

File: pkg/controller/v1beta1/inferenceservice/controller_test.go (hunk 3 above)
Comment (asdqwe123zxc) [reply pkg/controller/v1beta1/inferenceservice/controller_test.go:2192]: The code is modified to check if the event was published, thanks for the advice!

File: pkg/controller/v1beta1/inferenceservice/controller.go [hunk 5]
```diff
@@ -278,6 +278,14 @@ func (r *InferenceServiceReconciler) updateStatus(desiredService *v1beta1api.Inf
 		// This is important because the copy we loaded from the informer's
 		// cache may be stale and we don't want to overwrite a prior update
 		// to status with this stale state.
+
+		// Instead, if the model keep running on False state
+		// Raise an event for info of failed conditions.
+		if !wasReady {
+			msg := r.GetFailConditions(desiredService)
```
Comment (spolti) [inline pkg/controller/v1beta1/inferenceservice/controller.go]: as the msg var is only used here, we can remove it and call the function directly.

File: pkg/controller/v1beta1/inferenceservice/controller.go [hunk 6]
```diff
@@ -287,8 +295,9 @@ func (r *InferenceServiceReconciler) updateStatus(desiredService *v1beta1api.Inf
 		// If there was a difference and there was no error.
 		isReady := inferenceServiceReadiness(desiredService.Status)
 		if wasReady && !isReady { // Moved to NotReady State
+			msg := r.GetFailConditions(desiredService)
 			r.Recorder.Eventf(desiredService, v1.EventTypeWarning, string(InferenceServiceNotReadyState),
-				fmt.Sprintf("InferenceService [%v] is no longer Ready", desiredService.GetName()))
+				fmt.Sprintf("InferenceService [%v] is no longer Ready because of: %v", desiredService.GetName(), msg))
```
Comment (spolti) [inline pkg/controller/v1beta1/inferenceservice/controller.go]: same here.

File: pkg/controller/v1beta1/inferenceservice/controller_test.go [hunk 7]
```diff
@@ -1362,7 +1363,7 @@ var _ = Describe("v1beta1 inference service controller", func() {
 		})
 	})
 
-	Context("When creating an inference service with a ServingRuntime which is disabled", func() {
+	Context("When creating an inference service with a ServingRuntime which is disabled", func(){
```
Comment (spolti) [inline pkg/controller/v1beta1/inferenceservice/controller_test.go]: formatting issue?

**Review by spolti — COMMENTED** [review]
besides the minor comments, looks good.
Thanks.

/lgtm

**Review by spolti — APPROVED** [review]

File: pkg/controller/v1beta1/inferenceservice/controller_test.go (hunk 7 above)
Comment (asdqwe123zxc) [reply pkg/controller/v1beta1/inferenceservice/controller_test.go]: Sorry, this was our mistake. We will make the necessary corrections.

File: pkg/controller/v1beta1/inferenceservice/controller.go (hunk 6 above)
Comment (asdqwe123zxc) [reply pkg/controller/v1beta1/inferenceservice/controller.go]: Okay, thank you for your suggestion. We will make the adjustments.

File: pkg/controller/v1beta1/inferenceservice/controller.go (hunk 5 above)
Comment (asdqwe123zxc) [reply pkg/controller/v1beta1/inferenceservice/controller.go]: Okay, thank you for your suggestion. We will make the adjustments.

**Review by lizzzcai — APPROVED** [review]

File: pkg/controller/v1beta1/inferenceservice/controller.go [hunk 8]
```diff
@@ -278,6 +278,13 @@ func (r *InferenceServiceReconciler) updateStatus(desiredService *v1beta1api.Inf
 		// This is important because the copy we loaded from the informer's
 		// cache may be stale and we don't want to overwrite a prior update
 		// to status with this stale state.
+
+		// Instead, if the model keep running on False state
+		// Raise an event for info of failed conditions.
+		if !wasReady {
+			r.Recorder.Eventf(desiredService, v1.EventTypeWarning, string(InferenceServiceNotReadyState),
+				fmt.Sprintf("InferenceService [%v] is not Ready because of: %v", desiredService.GetName(), r.GetFailConditions(desiredService)))
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/controller.go]: This will keep printing the not ready event every time controller reconciles?

**Comment by yuzisun** [comment]
@asdqwe123zxc I think what we really want is to generate a event on the `LatestDeploymentReady` 
https://github.com/kserve/kserve/blob/74591b4a39b99aae8955072c04429824eb32ec07/pkg/apis/serving/v1beta1/inference_service_status.go#L122

File: pkg/controller/v1beta1/inferenceservice/controller.go [hunk 9]
```diff
@@ -288,7 +295,7 @@ func (r *InferenceServiceReconciler) updateStatus(desiredService *v1beta1api.Inf
 		isReady := inferenceServiceReadiness(desiredService.Status)
 		if wasReady && !isReady { // Moved to NotReady State
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/controller.go]: I think we should generate the event if wasReady && isReadyFalse to eliminate the false positive that generates the event for status unknown case.

Comment (yuzisun) [reply pkg/controller/v1beta1/inferenceservice/controller.go]: currently this block generates false ready event when the deployment is still in progress which marks the condition "unknown"

**Review by yuzisun — APPROVED** [review]
/lgtm
/approve
