### PR TITLE
Issue 4248: Request Logger with Multiple Metadata Headers fail

### LINKED ISSUE #4248: Request Logger with multiple metadata headers fails
/kind bug

**What steps did you take and what happened:**
Create an inference service with multiple headers with the following logger section in the predictor spec:
```
    logger:
      metadataHeaders:
        - Custom-Header1
        - Custom-Header2
```
and deploy the modified inference service with the message dumper noted here: https://kserve.github.io/website/0.14/modelserving/logger/logger/

When more than one header is sent, the metadata extension field in the CloudEvent is empty.  When only one header is sent, there is no issue.

**What did you expect to happen:**
Each header should be seen in the metadata extension field

**What's the InferenceService yaml:**
```
spec:
  predictor:
    canaryTrafficPercent: 100
    initContainers:
      - args:
          - [OMITTED]
        env:
          - name: KNATIVE_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['serving.knative.dev/service']
          - name: KNATIVE_CONFIGURATION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['serving.knative.dev/configuration']
          - name: KNATIVE_REVISION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['serving.knative.dev/revision']
          - name: PROMETHEUS_PUSHGATEWAY_URL
            value: OMITTED
        image: >-
          OMITTED
        name: storage-initializer
        resources: {}
        volumeMounts:
          - mountPath: /mnt/serving
            name: model-provision
    logger:
      metadataHeaders:
        - Custom-Header-1
        - Custom-Header-2 
      mode: all
      url: http://message-dumper.default/
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--model-store=/mnt/serving/model-store'
      modelFormat:
        name: OMITTED
      name: ''
      protocolVersion: v2
      resources:
        requests:
          cpu: '1'
          memory: 2Gi
      runtime: OMITTED
      storageUri: >-
       OMITTED
      volumeMounts:
        - mountPath: /mnt/serving
          name: model-provision
          readOnly: true
    serviceAccountName: OMITTED
    volumes:
      - emptyDir: {}
        name: model-provision
```
**Anything else you would like to add:**
I would like to solve this if possible since I believe I have found the issue :)

**Environment:**

- Istio Version: 1.22
- Knative Version: 1.13.1
- KServe Version: 1.14.0
- Kubeflow version: N/A
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]: aws
- Minikube/Kind version: N/A
- Kubernetes version: (use `kubectl version`): 1.30.2
- OS (e.g. from `/etc/os-release`): linux/amd64

### PR DESCRIPTION
**Pull request by tylerhyang**
**What this PR does / why we need it**:
The purpose of this commit is to fix metadata argument parsing.  Currently, the metadata headers for the logger are concatenated into a singular, comma-separated string.  This commit will segment the string at the commas to correctly generate the metadata headers.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4248 

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [x] Test 1: Deploying with new agent image successfully processes multiple metadata headers
- [x] Test 2: Deploying with new agent image with no metadata headers functions as expected

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
Enable multiple metadata headers for request logger
```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

File: cmd/agent/main.go [hunk 1]
```diff
@@ -285,6 +286,11 @@ func startLogger(workers int, logger *zap.SugaredLogger) *loggerArgs {
 		logger.Errorf("Malformed source_uri %s", *sourceUri)
 		os.Exit(-1)
 	}
+
+	var metadataHeadersParsed []string = []string{}
```
Comment (sivanantha321) [inline cmd/agent/main.go]: I think using [StringSlice](https://pkg.go.dev/github.com/spf13/pflag#StringSlice) instead of StringArray in the [flag definition](https://github.com/kserve/kserve/blob/e5b7919bc6061a429de15ab04bebf33943ed81f1/cmd/agent/main.go#L69) will fix the problem.

Comment (tylerhyang) [reply cmd/agent/main.go]: nice catch; much cleaner

**Comment by sivanantha321** [comment]
Thanks for the fix!
/lgtm
/approve
