### PR TITLE
4739 - Fix: blob storage for inference logging recognizes embedded spec

### LINKED ISSUE #4739: Blob store inference logging ignores spec, uses service level configmap
/kind bug

**What steps did you take and what happened:**

The pod mutator that sets up the agent injector is using the kserve inference service configmap for logger configuration, not the embedded logger spec.  

**What did you expect to happen:**

The logger configuration should use the embedded spec if it is defined, otherwise use the global configmap

### PR DESCRIPTION
**Pull request by cjohannsen-cloudera**
**What this PR does / why we need it**:

Fixes a bug in which the embedded logger spec was ignored and the global configmap for the services was used instead.  Now the embedded spec is used if populated and the global spec is the fallback.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4739

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.

Applied changes to cluster and instantiated an inference service with logging config embedded.  Observed that config was correctly detected and applied.

Updated unit test

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [x] Has code been commented, particularly in hard-to-understand areas?

**Release note**:
```release-note
NONE
```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

File: pkg/logger/store.go [hunk 1]
```diff
@@ -111,6 +111,7 @@ func NewStoreForScheme(scheme string, logStorePath string, logStoreFormat string
 		return nil, fmt.Errorf("failed to create S3 provider: %w", err)
 	}
 	if protocol == storage.S3 {
+		log.Infof("Using S3 Storage Provider")
```
Comment (houshengbo) [inline pkg/logger/store.go]: Do we really need to add this line, since it is too general with out mentioning service name?

File: pkg/webhook/admission/pod/agent_injector.go [hunk 2]
```diff
@@ -108,14 +108,22 @@ func getAgentConfigs(configMap *corev1.ConfigMap) (*AgentConfig, error) {
...
+	// default to the global inference service configmap
 	if loggerConfigValue, ok := configMap.Data[LoggerConfigMapKeyName]; ok {
 		err := json.Unmarshal([]byte(loggerConfigValue), &loggerConfig)
 		if err != nil {
 			panic(fmt.Errorf("Unable to unmarshall logger json string due to %w ", err))
 		}
 	}
+	if isvc != nil && isvc.Spec.Predictor.Logger != nil {
+		// if the inference service spec includes a logger spec, use it instead
+		log.Info("isvc contains a logging spec.  This will be used as the logger configuration.")
```
Comment (houshengbo) [inline pkg/webhook/admission/pod/agent_injector.go]: If we want it be more informative here, we need to at least add the name and the namespace for the inference service in this log message. Otherwise, all services logging the same info does not mean anything to us.

File: pkg/webhook/admission/pod/agent_injector.go [hunk 3]
```diff
@@ -108,14 +108,22 @@ func getAgentConfigs(configMap *corev1.ConfigMap) (*AgentConfig, error) {
...
+		loggerConfig.Store = isvc.Spec.Predictor.Logger.Storage
+	} else {
+		log.Info("isvc does not contain a logging spec.  The global configmap will be used as the logger configuration.")
```
Comment (houshengbo) [inline pkg/webhook/admission/pod/agent_injector.go]: This logging info also needs to be more concrete with specific service name under certain namespace.

File: pkg/webhook/admission/pod/agent_injector.go [hunk 4]
```diff
@@ -131,7 +139,6 @@ func getLoggerConfigs(configMap *corev1.ConfigMap) (*LoggerConfig, error) {
 		}
 	}
 	if loggerConfig.Store != nil {
-		log.Info("Using inference-service logger store configuration", "Store", loggerConfig.Store)
```
Comment (houshengbo) [inline pkg/webhook/admission/pod/agent_injector.go:134]: Why did you remove this line?

File: pkg/webhook/admission/pod/agent_injector.go [hunk 5]
```diff
@@ -238,10 +245,13 @@ func (ag *AgentInjector) InjectAgent(pod *corev1.Pod) error {
 			LoggerArgumentComponent,
 			component,
 		}
+		log.Info("Injecting logger configuration", "storagePath", storagePath)
```
Comment (houshengbo) [inline pkg/webhook/admission/pod/agent_injector.go]: If storagePath is empty, it logs nothing about the storagePath. Is this what you expected?

File: pkg/webhook/admission/pod/agent_injector.go [hunk 6]
```diff
@@ -238,10 +245,13 @@ func (ag *AgentInjector) InjectAgent(pod *corev1.Pod) error {
...
 		if storagePath != "" {
 			loggerArgs = append(loggerArgs, LoggerArgumentStorePath)
 			loggerArgs = append(loggerArgs, storagePath)
 		}
+
+		log.Info("Injecting logger configuration", "storageFormat", storageFormat)
```
Comment (houshengbo) [inline pkg/webhook/admission/pod/agent_injector.go]: If storageFormat is empty, it logs nothing about the storageFormat. Is this also what you expected?

File: pkg/webhook/admission/pod/agent_injector.go (hunk 5 above)
Comment (cjohannsen-cloudera) [reply pkg/webhook/admission/pod/agent_injector.go]: Nope, leftover debugging info that I will remove.

File: pkg/webhook/admission/pod/agent_injector.go (hunk 6 above)
Comment (cjohannsen-cloudera) [reply pkg/webhook/admission/pod/agent_injector.go]: Nope, leftover debugging info that I will remove.

File: pkg/webhook/admission/pod/agent_injector.go (hunk 4 above)
Comment (cjohannsen-cloudera) [reply pkg/webhook/admission/pod/agent_injector.go:134]: Accidental removal, adding back

File: pkg/logger/store.go (hunk 1 above)
Comment (cjohannsen-cloudera) [reply pkg/logger/store.go]: Removed

File: pkg/webhook/admission/pod/agent_injector.go (hunk 2 above)
Comment (cjohannsen-cloudera) [reply pkg/webhook/admission/pod/agent_injector.go]: Added in details for both name  and namespace and more informative message when no isvc is found

File: pkg/webhook/admission/pod/agent_injector.go (hunk 3 above)
Comment (cjohannsen-cloudera) [reply pkg/webhook/admission/pod/agent_injector.go]: Added in details for both name and namespace and more informative message when no isvc is found

File: pkg/webhook/admission/pod/agent_injector.go [hunk 7]
```diff
@@ -108,14 +108,26 @@ func getAgentConfigs(configMap *corev1.ConfigMap) (*AgentConfig, error) {
...
+	// default to the global inference service configmap
 	if loggerConfigValue, ok := configMap.Data[LoggerConfigMapKeyName]; ok {
 		err := json.Unmarshal([]byte(loggerConfigValue), &loggerConfig)
 		if err != nil {
 			panic(fmt.Errorf("Unable to unmarshall logger json string due to %w ", err))
 		}
 	}
+	if isvc != nil && isvc.Spec.Predictor.Logger != nil {
+		// if the inference service spec includes a logger spec, use it instead
+		log.Info("isvc contains a logging spec.  This will be used as the logger configuration.", "name", isvc.Name, "namespace", isvc.Namespace)
```
Comment (houshengbo) [inline pkg/webhook/admission/pod/agent_injector.go]:
```suggestion
		log.Info("The Inference Service contains a logging spec. This will be used as the logger configuration", "name", isvc.Name, "namespace", isvc.Namespace)
```

File: pkg/webhook/admission/pod/agent_injector.go [hunk 8]
```diff
@@ -108,14 +108,26 @@ func getAgentConfigs(configMap *corev1.ConfigMap) (*AgentConfig, error) {
...
+		loggerConfig.Store = isvc.Spec.Predictor.Logger.Storage
+	} else {
+		if isvc == nil {
+			log.Info("isvc not found.  The global configmap will be used as the logger configuration.", "namespace", pod.Namespace)
+		} else {
+			log.Info("isvc does not contain a logging spec.  The global configmap will be used as the logger configuration.", "names", isvc.Name, "namespace", isvc.Namespace)
```
Comment (houshengbo) [inline pkg/webhook/admission/pod/agent_injector.go]:
```suggestion
			log.Info("The Inference Service does not contain a logging spec. The global ConfigMap will be used as the logger configuration", "name", isvc.Name, "namespace", isvc.Namespace)
```

File: pkg/webhook/admission/pod/agent_injector.go [hunk 9]
```diff
@@ -108,14 +108,26 @@ func getAgentConfigs(configMap *corev1.ConfigMap) (*AgentConfig, error) {
...
 			panic(fmt.Errorf("Unable to unmarshall logger json string due to %w ", err))
 		}
 	}
+	if isvc != nil && isvc.Spec.Predictor.Logger != nil {
+		// if the inference service spec includes a logger spec, use it instead
+		log.Info("isvc contains a logging spec.  This will be used as the logger configuration.", "name", isvc.Name, "namespace", isvc.Namespace)
+		loggerConfig.Store = isvc.Spec.Predictor.Logger.Storage
+	} else {
+		if isvc == nil {
+			log.Info("isvc not found.  The global configmap will be used as the logger configuration.", "namespace", pod.Namespace)
```
Comment (houshengbo) [inline pkg/webhook/admission/pod/agent_injector.go]:
```suggestion
			log.Info("The Inference Service is not found. The global ConfigMap will be used as the logger configuration", "name", isvc.Name, "namespace", pod.Namespace)
```

**Review by houshengbo — APPROVED** [review]

**Review by yuzisun — APPROVED** [review]
