### PR TITLE
user defined model name overwrite issue fix

### LINKED ISSUE #2332: Kserve defaulting causing duplicates of environment variable
/kind bug

**What steps did you take and what happened:**
Create example xgboost isvc and enable gRPC
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "xgboost-iris"
spec:
  predictor:
    xgboost:
      protocolVersion: "v2"
      storageUri: "gs://kfserving-examples/models/xgboost/iris"
      ports:
      - containerPort: 9000
        name: h2c
        protocol: TCP
```

The pod spec has duplicated environment variable
```
    Environment:
      MLSERVER_MODEL_NAME:            xgboost-iris
      MLSERVER_MODEL_URI:             /mnt/models
      MLSERVER_MODEL_NAME:            xgboost-iris
      MLSERVER_MODEL_URI:             /mnt/models
```

Additionally, attempt to override the defaults leads to duplicated environment variable with different values

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "xgboost-iris"
spec:
  predictor:
    xgboost:
      protocolVersion: "v2"
      storageUri: "gs://kfserving-examples/models/xgboost/iris"
      ports:
      - containerPort: 9000
        name: h2c
        protocol: TCP
      env:
      - name: MLSERVER_MODEL_NAME
        value: my-model
```

The pod spec:
```
    Environment:
      MLSERVER_MODEL_NAME:            my-model
      MLSERVER_MODEL_NAME:            xgboost-iris
      MLSERVER_MODEL_URI:                /mnt/models
```

**What did you expect to happen:**
- Defaulting should not duplicate environment variable and should prioritise user's defined environment variable

**Anything else you would like to add:**
I believe it's because the defaulter always append `.Env` without checking the presence of existing environment variable. (https://github.com/kserve/kserve/blob/a6ed8e4b006e27433de2336e0e8b7cec11137dc1/pkg/apis/serving/v1beta1/inference_service_defaults.go#L264)

**Environment:**

- Kserve: 0.8.0

### PR DESCRIPTION
**Pull request by Suresh-Nakkeran**
Signed-off-by: Suresh Nakkeran <suresh.n@ideas2it.com>

**What this PR does / why we need it**:

- This PR is to address the user defined envs were overwritten by the default model server env issue. If the user provided custom model name as env variable that would also reflected in the inference service url.
- Fix IsMMSPredictor function as it incorrectly marks custom model server as MMS

**Which issue(s) this PR fixes**
fixes #2332 #2568 

**Type of changes**
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: pkg/utils/utils.go [hunk 1]
```diff
@@ -111,3 +111,19 @@ func IsPrefixSupported(input string, prefixes []string) bool {
...
 }
+
+func AppendEnvVarIfNotExists(slice []v1.EnvVar, elems ...v1.EnvVar) []v1.EnvVar {
+	for _, item := range elems {
+		appendEnvVarIfNotExists(slice, item)
+	}
+	return slice
+}
+
+func appendEnvVarIfNotExists(slice []v1.EnvVar, elem v1.EnvVar) []v1.EnvVar {
```
Comment (yuzisun) [inline pkg/utils/utils.go]: seems like it is cleaner to combine the two functions?

Comment (Suresh-Nakkeran) [reply pkg/utils/utils.go]: updated!

File: pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go [hunk 2]
```diff
@@ -373,10 +373,19 @@ func (ir *IngressReconciler) Reconcile(isvc *v1beta1.InferenceService) error {
 		}
 		if !isvcutils.IsMMSPredictor(&isvc.Spec.Predictor, isvcConfig) {
 			protocol := isvc.Spec.Predictor.GetImplementation().GetProtocol()
+			modelName := isvc.Name
+			// Set model name from env variable for mlserver
+			if isvc.Spec.Predictor.Model != nil {
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go]: Hmm actually each model server has ways to overwrite the model name, not sure how to handle this systematically or maybe we can treat this field as default model url

Comment (pradithya) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go]: To add additional context to https://github.com/kserve/kserve/issues/2332. I'd like to have different value for isvc.name and the mlserver model name. So I don't think we should add ability to override isvc.name using env. 

The reason to have different value is for having different host and the model_name value in the request payload when calling a model. As of now, it must always be the same. 
E.g if I have isvc.name = "my-model". It will generate host `my-model.<namespace>.<base_url>` and the model payload should contains "model_name" = "my-model" field.  In my case I would like to keep the expected "model_name" in the payload to be the same for several isvc by overriding `MODEL_NAME` env var so that I could introduce some traffic shaping in front of these models.

Comment (yuzisun) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go]: @pradithya here it is overriding the model name in the url path not the host, the host is still using the isvc name, I think that’s what you expected.

Comment (pradithya) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go]: Yes correct, that's my intention.
