### PR TITLE
Fix Gateway API flaky test

### LINKED ISSUE #4211: Flaky test for gateway API raw deployment mode
/kind bug

**What steps did you take and what happened:**
```
2025-01-26T01:57:00Z	INFO	IngressReconciler	Predictor HTTPRoute not ready	{"reason": "ParentStatusNotAvailable", "message": "HttpRouteNotReady"}
  [FAILED] in [It] - /home/runner/work/kserve/kserve/pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go:560 @ 01/26/25 01:58:00.867
  << Timeline

  [FAILED] Timed out after 60.000s.
  Expected
      <string>:   &v1beta1.InferenceServiceStatus{
        	Status: v1.Status{
        		ObservedGeneration: 0,
        		Conditions: v1.Conditions{
        			{
        				Type:     "IngressReady",
      - 				Status:   "True",
      + 				Status:   "False",
        				Severity: "",
        				... // 1 ignored field
      - 				Reason:  "",
      + 				Reason:  "ParentStatusNotAvailable",
      - 				Message: "",
      + 				Message: "Predictor HttpRouteNotReady",
        			},
        			{Type: "PredictorReady", Status: "True"},
        			{
        				Type:     "Ready",
      - 				Status:   "True",
      + 				Status:   "False",
        				Severity: "",
        				... // 1 ignored field
      - 				Reason:  "",
      + 				Reason:  "ParentStatusNotAvailable",
      - 				Message: "",
      + 				Message: "Predictor HttpRouteNotReady",
        			},
        		},
        		Annotations: nil,
        	},
      - 	Address:     &v1.Addressable{URL: s"http://raw-foo-predictor.default.svc.cluster.local/"},
      + 	Address:     nil,
      - 	URL:         s"http://raw-foo-default.example.com/",
      + 	URL:         nil,
        	Components:  {"predictor": {URL: &{Scheme: "http", Host: "raw-foo-predictor-default.example.com"}}},
        	ModelStatus: {TransitionStatus: "InProgress", ModelRevisionStates: &{TargetModelState: "Pending"}},
        }
      
  to be empty
  In [It] at: /home/runner/work/kserve/kserve/pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go:560
```

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by sivanantha321**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4211

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [x] Test A
  Tested with following script. The error hadn't occurred in 200 runs.
```bash
#! /bin/bash

set -o errexit
set -o nounset
set -o pipefail

for i in {1..200}; do
    echo "################################ Run $i ################################"
    ginkgo run --json-report ./ginkgo.report \
    -focus "v1beta1 inference service controller When creating inference service with raw kube predictor Should have httproute/service/deployment/httproute created" \
    ./pkg/controller/v1beta1/inferenceservice
done
```

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
NONE
```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

File: pkg/controller/v1alpha1/inferencegraph/suite_test.go [hunk 1]
```diff
@@ -81,22 +81,10 @@ var _ = BeforeSuite(func() {
 	err = netv1.AddToScheme(scheme.Scheme)
 	Expect(err).NotTo(HaveOccurred())
 
-	k8sClient, err = client.New(cfg, client.Options{Scheme: scheme.Scheme})
```
Comment (sivanantha321) [inline pkg/controller/v1alpha1/inferencegraph/suite_test.go:84]: Tests are creating two k8s clients one with cache and one with no cache. One with the cache is used by the controller while the test itself is using client without cache. It sometimes leads to inconsistencies in getting the resources. This PR removes client with no cache and uses client with cache for both controller and tests.

Comment (yuzisun) [reply pkg/controller/v1alpha1/inferencegraph/suite_test.go:84]: Good catch!

File: pkg/controller/v1alpha1/inferencegraph/suite_test.go [hunk 2]
```diff
@@ -105,6 +93,17 @@ var _ = BeforeSuite(func() {
 	})
 	Expect(err).ToNot(HaveOccurred())
 
+	k8sClient = k8sManager.GetClient()
+	Expect(k8sClient).ToNot(BeNil())
+
+	//Create namespace
+	kfservingNamespaceObj := &v1.Namespace{
```
Comment (yuzisun) [inline pkg/controller/v1alpha1/inferencegraph/suite_test.go]: Kfserving -> kserve

**Review by spolti — APPROVED** [review]
