### PR TITLE
fix: Hostname Generation for Additional Ingress Domains in RawDeployment Mode

### LINKED ISSUE #4323: Kserve rawDeployment mode with wrong hostName in additionalIngressDomains
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Hi, we run Kserve rawDeployment mode and set

```
"ingressDomain"  : "inference-qa.dsp.dev.foo.com"
"additionalIngressDomains": ["inference-qa.dsp.dev.bar.com"]
```

We depoly a InferenceService called `isvc-custom` in the `default` namespace, the `HTTPRoute` is the following
```
isvc-custom     ["isvc-custom-default.inference-qa.dsp.dev.foo.com", "inference-qa.dsp.dev.bar.com"]
```
The hostName for additional domain is not correct.

**What did you expect to happen:**

We expect
```
isvc-custom     ["isvc-custom-default.inference-qa.dsp.dev.foo.com", "isvc-custom-default.inference-qa.dsp.dev.bar.com"]
```

I think the [GenerateDomainName](https://github.com/kserve/kserve/blob/master/pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/httproute_reconciler.go#L196) should be applied on additionalIngressDomain

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:  1.24.0
- Knative Version: X
- KServe Version: v0.15.0-rc1
- Kubeflow version: X
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version: 
- Kubernetes version: (use `kubectl version`): 1.29
- OS (e.g. from `/etc/os-release`): ubuntu jammy

### PR DESCRIPTION
**Pull request by sivanantha321**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4323

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [x] Has code been commented, particularly in hard-to-understand areas?

**Release note**:

```release-note
fix: Hostname Generation for Additional Ingress Domains in RawDeployment Mode
```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

File: pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/domain.go [hunk 1]
```diff
@@ -91,3 +92,58 @@ func GenerateInternalDomainName(name string, obj metav1.ObjectMeta, ingressConfi
...
+//
+//	A pointer to a slice of additional valid hostnames created by combining the extracted subdomain
+//	with each domain in the additionalIngressDomains. Returns an empty slice if no additional hostnames
+//	can be created or if additionalIngressDomains is not configured.
+//
+// Note:
+//   - The function extracts a subdomain from the serviceHost by checking against domains in domainList
+//   - The function validates each generated hostname using DNS validation rules
+//   - Duplicate domains in the additionalIngressDomains are automatically deduplicated
+func GetAdditionalHosts(domainList *[]string, serviceHost string, config *v1beta1.IngressConfig) *[]string {
```
Comment (spolti) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/domain.go:114]: it would be nice to add a check to make sure that the generated URLs will not pass the maximum value allowed (63 IIRC).
We had a issue on our side that it would happen, if the domain template is too big, we would have this issue.

Comment (sivanantha321) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/domain.go:114]: Sure.

Comment (sivanantha321) [reply pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/domain.go:114]: Actually, Only the individual labels (segments between dots in a fully qualified domain name) are limited to 63 characters. When the entire domain name (or subdomain) is considered, it can be up to 253 characters long.
The validation for the full domain name is already handled here. As for the individual label validation, I think this is not the right place to do the validation. The label validation should be handled before the primary domain generation.

**Review by yuzisun — APPROVED** [review]
