### PR TITLE
Fix failure to create gRPC isvc when specifying multiple ContainerPorts

### LINKED ISSUE #2376: Failure to create gRPC InferenceService when specifying multiple ContainerPorts
/kind bug

Opening the issue based on conversation in Slack: https://kubeflow.slack.com/archives/CH6E58LNP/p1659980003450359

**What steps did you take and what happened:**
When trying to create a gRPC InferenceService following https://kserve.github.io/website/0.8/modelserving/v1beta1/tensorflow/#create-the-grpc-inferenceservice guide, and providing multiple port configs like below
```
...
      ports:
        - containerPort: 9000
          name: h2c
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
```
in the K8s Service, only the h2c port would appear:
```
...
spec:
  ports:
    - name: my-model-server-predictor-default
      protocol: TCP
      port: 80
      targetPort: 9000
```

**What did you expect to happen:**
That the port configs are all present in the K8s Service

**Anything else you would like to add:**
I am using the RawDeployment installation mode.

**Environment:**

- Istio Version:
  - (from `istioctl version`)
    ```
    control plane version: 1.14.1
    data plane version: 1.14.1 (150 proxies)
    ```
- Knative Version: N/A
- KFServing Version: 0.8.0
- Kubeflow version: N/A
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]: N/A
- Minikube version: N/A
- Kubernetes version: (use `kubectl version`): `v1.21.13-eks-84b4fe6`
- OS (e.g. from `/etc/os-release`):
  ```
  NAME="Ubuntu"
  VERSION="18.04.6 LTS (Bionic Beaver)"
  ```

### PR DESCRIPTION
**Pull request by andyi2it**
Signed-off-by: Andrews Arokiam <andrews.arokiam@ideas2it.com>

**What this PR does / why we need it**:
Made changes to copy ports in service reconciler to target service.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2376 

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**Feature/Issue validation/testing**:

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go [hunk 1]
```diff
@@ -71,23 +71,51 @@ func createService(componentMeta metav1.ObjectMeta, componentExt *v1beta1.Compon
...
+			Name: componentMeta.Name,
+			Port: constants.CommonDefaultHttpPort,
+			TargetPort: intstr.IntOrString{
+				Type:   intstr.Int,
+				IntVal: int32(port),
+			},
+			Protocol: corev1.ProtocolTCP,
+		},
+	}
+	for i := 1; i < len(podSpec.Containers[0].Ports); i++ {
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go]: Seems like we are skipping the first port, what happens when gRPC port is specified first so we will potentially have duplicated http ports

File: pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go [hunk 2]
```diff
@@ -71,23 +71,51 @@ func createService(componentMeta metav1.ObjectMeta, componentExt *v1beta1.Compon
...
-					Name: componentMeta.Name,
-					Port: constants.CommonDefaultHttpPort,
-					TargetPort: intstr.IntOrString{
-						Type:   intstr.Int,
-						IntVal: int32(port),
-					},
-					Protocol: corev1.ProtocolTCP,
-				},
-			},
+			Ports: ports,
```
Comment (yuzisun) [inline pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go]: Also let's add a test for gRPC test, I do not think we have one for `RawDeployment` mode.
