### PR TITLE
Fixed the CA bundle env var logic

### LINKED ISSUE #4761: spec.initContainers[0].env[1].valueFrom: Invalid value: ""
/kind bug

**What steps did you take and what happened:**

When I create the inference service, it failed to launch the pod. The deployment is there, but not the pod.
The deployment resource gave me the following error:
```
[spec.initContainers[0].env[1].valueFrom: Invalid value: "": may not be specified
      when `value` is not empty, spec.initContainers[0].env[2].valueFrom: Invalid
      value: "": may not be specified when `value` is not empty]
```

This error seems to indicate conflicting value and valueFrom fields set in the container env.
The error was introduced by this PR: https://github.com/kserve/kserve/pull/4726

If we remove the section 
```
			Env: []corev1.EnvVar{
				{
					Name:  "HF_HUB_ENABLE_HF_TRANSFER",
					Value: "1",
				},
				{
					Name:  "HF_XET_HIGH_PERFORMANCE",
					Value: "1",
				},
				{
					Name:  "HF_XET_NUM_CONCURRENT_RANGE_GETS",
					Value: "8",
				},
			},
```
from the file pkg/utils/storage.go, the issue is gone.

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by houshengbo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4761

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

File: pkg/controller/v1alpha1/llmisvc/workload_storage.go [hunk 1]
```diff
@@ -283,15 +283,31 @@ func injectCaBundle(namespace string, podSpec *corev1.PodSpec, initContainer *co
...
-		})
-
-		initContainer.Env = append(initContainer.Env, corev1.EnvVar{
-			Name:  constants.CaBundleVolumeMountPathEnvVarKey,
-			Value: caBundleVolumeMountPath,
-		})
+		// Add CA bundle env vars only if they don't already exist (could be customized by user)
+		caBundleEnvVarExists := false
+		caBundleMountPathEnvVarExists := false
+		for _, envVar := range initContainer.Env {
```
Comment (brettmthompson) [inline pkg/controller/v1alpha1/llmisvc/workload_storage.go]: nit: this could be consolidated into the for loop above

**Comment by brettmthompson** [comment]
LGTM

**Comment by Jooho** [comment]
@houshengbo Do you have an issue for this PR? or could you please update description? I wonder what the issue was that you hit. (I understand what issue was there from the code change but just for reference, it would be a good idea to have accurate inforamtion in descrption)

File: pkg/controller/v1alpha1/llmisvc/workload_storage.go (hunk 1 above)
Comment (Jooho) [reply pkg/controller/v1alpha1/llmisvc/workload_storage.go]: As @brettmthompson mentioned, there’s repeated logic around setting caBundleConfigMapName and caBundleVolumeMountPath. Might be cleaner to refactor into a helper or single pass.

**Review by Jooho — COMMENTED** [review]
Logic is good to me but I am not a fan of duplication 😆 can we clean this up a bit?

**Comment by brettmthompson** [comment]
@Jooho https://github.com/kserve/kserve/issues/4761

File: pkg/controller/v1alpha1/llmisvc/workload_storage.go (hunk 1 above)
Comment (houshengbo) [reply pkg/controller/v1alpha1/llmisvc/workload_storage.go]: Just merged them.

**Comment by Jooho** [comment]
What @brettmthompson mentioned from [here](https://github.com/kserve/kserve/issues/4761#issuecomment-3432670543) is exactly the main reason behind this PR?  Then, looks like you already fixed the duplicate env issue with another PR.. What issue you want to solve with this PR then?

Moreover, storage_initializer_injector has similar logic for this. Should we not need this changes for storage_initializer_injector.go?

**Comment by brettmthompson** [comment]
@Jooho https://github.com/kserve/kserve/pull/4765 covers the storage_initializer_injector

This PR applies the same changes to the ca bundle injection logic used for llmisvcs

**Review by Jooho — APPROVED** [review]
/lgtm
/approve
