### PR TITLE
fix: Adds support for NVIDIA MIG GPU resource detection

### LINKED ISSUE #4640: Is default image of HuggingFace server non-GPU in 0.15?
/kind bug

**What steps did you take and what happened:**

We updated our KServe setup from 0.14 to latest 0.15.2 version and all our LLM models with HuggingFace serving runtime crashed because there is no support for GPU in new version by default.

**What did you expect to happen:**

Since two types of kserve/huggingfaceserver image have started from 0.15.* version (GPU and non-GPU) we expected that default values will still be GPU latest tag. 
Here we see that the default version is non-GPU: https://github.com/kserve/kserve/blob/master/charts/kserve-resources/values.yaml#L332

**What's the InferenceService yaml:**

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: huggingface-llama3
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=llm_model
        - --model_id=Qwen/Qwen2.5-14B-Instruct
        - --max-model-len=2048
      env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN
              optional: false
      resources:
        limits:
          cpu: "6"
          memory: 24Gi
          nvidia.com/mig-7g.80gb: "1"
        requests:
          cpu: "6"
          memory: 24Gi
          nvidia.com/mig-7g.80gb: "1"
```

I'm confused because it's not compatible and it took several hours to find out that there is problem in the image, not the hardware.
Please help! Maybe we are doing smth wrong and somehow incorrectly updated KServe charts.

- KServe Version: 0.15.2
- Cloud Environment: Kubernetes

### PR DESCRIPTION
**Pull request by sivanantha321**
Extends GPU detection logic to recognize NVIDIA MIG resource names, enabling accurate identification of GPU-enabled workloads using MIG instances. Updates tests to cover MIG GPU scenarios for improved reliability.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4640

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [x] Has code been commented, particularly in hard-to-understand areas?

**Release note**:

```release-note
NONE
```

**Re-running failed tests**

### CODE REVIEW

File: pkg/utils/utils.go [hunk 1]
```diff
@@ -55,7 +55,17 @@ func AppendVolumeIfNotExists(slice []corev1.Volume, volume corev1.Volume) []core
...
 func IsGPUEnabled(requirements corev1.ResourceRequirements) bool {
 	_, ok := requirements.Limits[constants.NvidiaGPUResourceType]
-	return ok
+	if ok {
+		return true
+	}
+	for resourceName, _ := range requirements.Limits {
+
+	// Check if the resource name has the MIG prefix
+	if strings.HasPrefix(string(resourceName), constants.NvidiaMigGPUResourceTypePrefix) {
```
Comment (gavrissh) [inline pkg/utils/utils.go]: In `IsGPUEnabled()`, we check only for NvidiaTypes?

Comment (sivanantha321) [reply pkg/utils/utils.go]: We are only providing prebuilt  Nvidia cuda gpu images, right ?

Comment (gavrissh) [reply pkg/utils/utils.go]: Got it, Thanks!

**Review by yuzisun — APPROVED** [review]
